Repository gitextensions/gitextensions, pull requests merged in 2018-07, with the labels that each got.

#5128 git-diff parsing of unmerged and staged
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitItemStatus.cs
  GitCommands/Git/GitModule.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/FormArchive.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/Editor/FileViewer.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid.cs
  GitUI/UserControls/ToolStripClasses/CommitIconProvider.cs
  UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
  UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs
  UnitTests/GitUITests/UserControls/ToolStripClasses/CommitIconProviderTests.cs
Labels: ready

#5102 Fixing mergetool (setting) status message
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: ready

#5129 Distinguish between "Stash changes" and "Manage stashes"
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/Translation/English.xlf
  GitUI/Translation/German.xlf
Labels: feature request, user experience

#5100 Added "Select All" feature to Delete Unused Branches plugin
  Plugins/DeleteUnusedBranches/CheckBoxHeaderCellEventArgs.cs
  Plugins/DeleteUnusedBranches/DataGridViewCheckBoxHeaderCell.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Labels: status: ready

#5169 Include System.ValueTuple in portable archive
  Setup/MakePortableArchive.cmd
Labels: area: installer

#5183 Fixed Bitbucket plugin error on non-Bitbucket repo
  Plugins/Bitbucket/BitbucketPlugin.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/Bitbucket/Settings.cs
Labels: status: ready

#5214 Add remote tree icon for VSTS remotes
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/VisualStudioTeamServices.png
Labels: area: user experience

#5231 Cleanup: WorkTree/Index should be used rather than Unstaged/Staged
  GitCommands/Git/Extensions/GitRevisionExtensions.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitRevision.cs
  GitCommands/Git/RevisionDiffProvider.cs
  GitCommands/Patches/PatchManager.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FileStatusListContextMenuController.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUICommands.cs
  GitUI/UserControls/RepoStateVisualiser.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  Plugins/GitUIPluginInterfaces/ObjectId.cs
  ResourceManager/LinkFactory.cs
  UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
  UnitTests/GitCommandsTests/Git/Extensions/GitRevisionExtensionsTests.cs
  UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
  UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs
  UnitTests/GitCommandsTests/Git/ObjectIdTests.cs
  UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs
  UnitTests/GitUITests/CommandsDialogs/RevisionDiffContextMenuControllerTests.cs
  UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs
  UnitTests/GitUITests/UserControls/RepoStateVisualiserTests.cs
  UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Labels: status: ready

#5240 GitModule uses ObjectId in a few more places
  GitCommands/ArgumentBuilder.cs
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormBlame.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/UserControls/BranchSelector.cs
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Labels: status: ready
