Repository gitextensions/gitextensions, pull requests merged in 2018-08, with the labels that each got.

#5096 Added {UserFile} option to list
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  GitUI/GitUI.csproj
  GitUI/Script/FormFilePrompt.Designer.cs
  GitUI/Script/FormFilePrompt.cs
  GitUI/Script/FormFilePrompt.resx
  GitUI/Script/ScriptRunner.cs
Labels: status: ready

#5285 Add two patterns to C# AutoCompleteRegexes
  GitExtensions/AutoCompleteRegexes.txt
Labels: type: feature request

#5349 Reduce number of graph refreshes
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: area: performance

#5342 Add setting to maximize the commit message column
  GitUI/UserControls/RevisionGrid/Columns/AuthorNameColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#5367 A removed submodule raised an Exception
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitSubmoduleStatus.cs
Labels: status: ready
