Repository gitextensions/gitextensions, pull requests merged in 2018-11, with the labels that each got.

#5622 Issue 5616: Provide a way to remove all invalid recent repositories.
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: waffle:needs review

#5679 fix: FormCommit default button
  GitUI/CommandsDialogs/FormCommit.cs
Labels: waffle:ready

#5675 Fix issue 5672: The caches can be reset, make sure to use the same instance
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Labels: status: ready, waffle:ready

#5685 #5658 Update node cache to fix quick search
  GitCommands/Git/GitRevisionTester.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Labels: status: needs review

#5688 Move donations from PayPal to Open Collective
  GitUI/CommandsDialogs/BrowseDialog/FormDonate.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
  GitUI/CommandsDialogs/BrowseDialog/FormDonate.resx
  GitUI/CommandsDialogs/FormAbout.Designer.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/Donate.jpg
  GitUI/Resources/Icons/Donate.png
  GitUI/Resources/Icons/artwork/opencollective.svg
  GitUI/Translation/Czech.xlf
  GitUI/Translation/Dutch.xlf
  GitUI/Translation/English.xlf
  GitUI/Translation/French.xlf
  GitUI/Translation/German.xlf
  GitUI/Translation/Italian.xlf
  GitUI/Translation/Japanese.xlf
  GitUI/Translation/Korean.xlf
  GitUI/Translation/Polish.xlf
  GitUI/Translation/Portuguese (Brazil).xlf
  GitUI/Translation/Portuguese (Portugal).xlf
  GitUI/Translation/Romanian.xlf
  GitUI/Translation/Russian.xlf
  GitUI/Translation/Simplified Chinese.xlf
  GitUI/Translation/Spanish.xlf
  GitUI/Translation/Traditional Chinese.xlf
  GitUI/Translation/en_pseudo.Plugins.xlf
  GitUI/Translation/en_pseudo.xlf
  README.md
Labels: status: ready

#5671 Fix incorrect v-position for parent centered windows
  GitUI/GitExtensionsForm.cs
  GitUI/WindowPositionManager.cs
  UnitTests/GitUITests/GitExtensionsFormTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: waffle:ready

#5691 Text when no common ancestors assumed 2 commits
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#5681 Avoid automatic quotes on FileFilter value.
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
Labels: waffle:needs review

#5664 Avoid automatic quotes on FileFilter value.
  GitUI/UserControls/RevisionGridClasses/FormRevisionFilter.cs
Labels: waffle:needs review

#5670 #5665 Commit info not sized correctly
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommitInfo/CommitInfo.Designer.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.Designer.cs
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/DoubleBufferedTableLayoutPanel.cs
  GitUI/UserControls/FileStatusList.cs
  ResourceManager/GitExtensionsControlInitialiser.cs
Labels: status: ready, waffle:needs review

#5668 Prevent clipping of environment info
  GitUI/CommandsDialogs/EnvironmentInfo.cs
  GitUI/CommandsDialogs/FormAbout.Designer.cs
  GitUI/UserEnvironmentInformation.cs
Labels: status: ready, waffle:needs review

#5689 Increase contrast of blue branch and selected row
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
Labels: status: needs review

#5696 Update recommended Git version to 2.19.1
  GitCommands/Git/GitVersion.cs
Labels: status: ready

#5700 Revision graph distorted #5673
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
Labels: status: needs review

#5513 Fix issues identified by running TranslationApp
  GitUI/CommandsDialogs/EnvironmentInfo.cs
  GitUI/CommandsDialogs/FormAbout.Designer.cs
  GitUI/CommandsDialogs/FormAbout.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/GitModuleForm.cs
  GitUI/Properties/AssemblyInfo.cs
  GitUI/Translation/UpdateLocalEnglishTranslations.ps1
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  TranslationApp/Program.cs
Labels: status: ready

#5701 File status list width
  GitUI/UserControls/FileStatusList.cs
Labels: status: ready

#5699 Git Version check was removed from settings
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
Labels: status: ready

#5708 Copy commit message when copy commit info is used
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#5692 Activating Open Collective
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: status: ready

#5709 Apply AppSettings.CommitFont to rtbxCommitMessage
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: needs review

#5634 Allow esc key in commit diff to close FormCommit
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
Labels: status: ready, waffle:ready

#5706 5703: Fix System.ArgumentException when loading graph
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Labels: status: ready

#5715 Prevent duplicate fixup!/squash! prefix
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: ready

#5686 Fix RemoteObjectTree branch folder nodes sometimes becoming bold
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Labels: area: left-panel, prio:high, type: regression

#5720 Retrieve worktrees for the current module.
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
Labels: status: ready

#5710 Readme tweak
  GitUI/Resources/Icons/originals/jetbrains-variant-4.png
  README.md
Labels: status: ready

#5716 Don't allocate for every Windows message
  GitUI/UserControls/ExListView.cs
Labels: status: ready

#5723 Cleanup selection code
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommandsTests/Git/ObjectIdTests.cs
Labels: status: ready

#5724 Fixed null reference when hovering over lane in graph
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
Labels: status: ready

#5690 Fix GetSubmodulesLocalPaths(recursive: true) not actually recursing d…
  GitCommands/Git/GitModule.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: needs review

#5722 Fixed issue that Dashboard is not shown when it should. Loading indicator keeps spinning
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUICommands.cs
Labels: status: ready

#5729 Remove untranslatable strings
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Labels: status: ready

#5728 Fixed issue that 'Show first parent' only works when 'Current branch only' is also enabled
  GitCommands/RevisionReader.cs
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/RevisionReaderTests.cs
Labels: status: ready

#5736 Copy SHA via Ctrl+C broken
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
Labels: status: ready

#5738 Browse: Inconsistent behavior for Refresh button and F5/Repository-menu
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#5737 Add DPI scale to environment info
  GitUI/UserEnvironmentInformation.cs
Labels: status: needs review

#5712 Added multithreading test and fixed issues
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
Labels: prio:high, status: ready, type: regression

#5725 EditNetSpell: Double click marks the whole word (including underscores)
  GitUI/SpellChecker/EditNetSpell.cs
  GitUI/SpellChecker/SpellCheckerHelper.cs
  GitUI/SpellChecker/WordAtCursorExtractor.cs
  UnitTests/GitUITests/SpellChecker/WordAtCursorExtractorTests.cs
Labels: status: needs review

#5752 Fix commit dialog not refreshing on focus
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: ready

#5755 Include missing assembly in portable build
  Setup/MakePortableArchive.cmd
Labels: status: needs review

#5757 About layout
  GitUI/CommandsDialogs/FormAbout.cs
Labels: status: needs review

#5749 Differentiate rename between identical and modified
  GitUI/UserControls/FileStatusList.cs
Labels: status: needs review

#5756 submodule status configurable
  GitCommands/Settings/AppSettings.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/FormSettings.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
Labels: status: ready

#5740 Show correct tooltips for graph lanes
  GitUI/GitUI.csproj
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
  GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs
  ResourceManager/Strings.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneNodeLocatorTests.cs
Labels: status: ready

#5748 Refresh reset current branch layout
  GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
  GitUI/HelperDialogs/FormResetCurrentBranch.resx
  GitUI/UserControls/CommitSummaryUserControl.Designer.cs
  GitUI/UserControls/CommitSummaryUserControl.cs
  GitUI/UserControls/CommitSummaryUserControl.resx
Labels: area: user experience, status: ready

#5765 Invoke pull dialog with autoPullAction when push is rejected.
  GitUI/CommandsDialogs/FormPush.cs
Labels: status: ready

#5772 Jira Commit Hint plugin can't load
  Setup/MakePortableArchive.cmd
Labels: status: ready

#5754 Do not crash if git.exe is not found
  GitExtensions/GitExtensions.csproj
  GitExtensions/Program.cs
  GitExtensions/app.manifest
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  ResourceManager/Strings.cs
  UnitTests/GitCommandsTests/MockExecutable.cs
Labels: status: ready

#5763 Show the output produced in ProcessExited event handlers.
  GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Labels: status: ready, type: regression

#5779 Fix RepoObjectsTree (left panel) remaining blank when ReloadAsync is …
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: status: needs review

#5746 Improve clipboard set-text operations
  GitExtUtils/ClipboardUtil.cs
  GitExtUtils/GitExtUtils.csproj
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormReflog.cs
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/Editor/FileViewer.cs
  GitUI/UserControls/BlameControl.cs
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserEnvironmentInformation.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs
Labels: status: ready

#5759 Make portable build use portable config
  Setup/MakePortableArchive.cmd
  Setup/Prepare-Release.ps1
  Setup/Set-Portable.ps1
  appveyor.yml
Labels: status: needs review

#5784 Update links to application dependencies wiki page
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
Labels: area: documentation, status: ready

#5794 Link Translations to wiki page
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  README.md
Labels: status: ready

#5762 Tweak presentation of DPI info on the "About" form
  CommonAssemblyInfo.cs
  GitUI/CommandsDialogs/EnvironmentInfo.Designer.cs
  GitUI/CommandsDialogs/EnvironmentInfo.cs
  GitUI/CommandsDialogs/FormAbout.Designer.cs
  GitUI/CommandsDialogs/FormAbout.cs
  GitUI/UserEnvironmentInformation.cs
  UnitTests/GitUITests/TranslationTest.cs
Labels: status: ready

#5795 Tweak the dashboard light colour scheme
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardTheme.cs
  GitUI/Resources/Backgrounds/DashboardBackgroundBlue.png
  Logo/GitExtensionsLogoWide.png
Labels: status: ready

#5792 #5764 Crash when pressing F5 while hovering item in dashboard
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: status: needs review

#5800 Improve time complexity of IndexOf.
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready, type: bug

#5803 Fix clone dialog doesn't pick up destination
  GitUI/CommandsDialogs/FormClone.cs
Labels: status: ready

#5775 Issue 4885 - Integration of PluginManager
  .gitignore
  Setup/Download-PluginManager.ps1
  Setup/MakePortableArchive.cmd
  Setup/PluginManager.wxs
  Setup/Prepare-Release.ps1
  Setup/Product.wxs
  Setup/Setup.wixproj
Labels: area: installer, area: plugins, status: needs review

#5808 Limits RevisionsSplitContainer.SplitterDistance to a min of 0
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#5820 Add try catch around method to guess system encoding.
  GitCommands/Git/GitModule.cs
Labels: prio:high, status: ready, type: bug, type: regression

#5821 Fixed #5811: strange resize of the description column when selecting lines with mouse click
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready, type: regression
