Repository gitextensions/gitextensions, pull requests merged in 2018-10, with the labels that each got.

#5490 Browse: Throttle submodule status updates
  GitCommands/Submodules/SubmoduleStatusProvider.cs
Labels: status: ready, type: regression

#5522 Fixed null reference exception
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#5537 Prevent showing async loaded data for a revision it was not loaded for.
  GitUI/CommitInfo/CommitInfo.cs
Labels: type: bug

#5576 Fix a typo introduced in #5480.
  GitUI/CommandsDialogs/FormPull.cs
Labels: waffle:ready

#5577 fix: GPG tab icons not scaled
  GitUI/CommandsDialogs/RevisionGpgInfoControl.cs
Labels: area: hdpi, waffle:ready

#5581 Fix SubmoduleInfoResult having no CurrentSubmoduleName for submodules…
  GitCommands/Git/GitModule.cs
Labels: waffle:needs review

#5579 FormFormatPatch: Do not show artificial commits
  GitUI/CommandsDialogs/FormFormatPatch.cs
Labels: waffle:ready

#5584 Fix FormCommit status branch icon width at high DPI
  GitUI/CommandsDialogs/FormCommit.cs
Labels: area: hdpi, waffle:ready

#5585 Increase initial object tree width
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: area: hdpi, waffle:ready

#5586 Performance improvements for object tree rendering
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: waffle:ready

#5591 Clear revisiongrid before start reading log
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: waffle:ready

#5592 Fix branches and tags copying.
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Labels: waffle:ready

#5595 Fixed issue #5594: Setting order revisions by date has no effect
  GitCommands/RevisionReader.cs
Labels: waffle:ready

#5588 Browse: Change icon for submodule menu
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: waffle:ready

#5587 Clarify "Go to merge base commit" menu option text
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Labels: waffle:needs review

#5600 Tweak the build script
  Setup/Build.cmd
  Setup/BuildInstallers.cmd
  appveyor.yml
Labels: waffle:ready

#5603 fix: Reinstate CopyContextMenuItem shortcuts
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
  ResourceManager/Strings.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
Labels: waffle:ready

#5602 Tweak the build script
  Setup/BuildArtifacts.cmd
  Setup/BuildGitExtNative.cmd
  Setup/BuildInstallers.VS2015.cmd
  Setup/MakeMonoArchive.cmd
  Setup/Setup.wixproj
  appveyor.yml
Labels: waffle:ready

#5596 When ordering is unspecified use "topo-order" to prevent parents showing before all of their children are shown
  GitCommands/RevisionReader.cs
Labels: waffle:needs review

#5613 Expose chkConfirmStashDrop in Confirmations Settings page
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
Labels: waffle:needs review

#5619 Fix #5618 FileViewer: Find next/previous change
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/IFileViewer.cs
Labels: waffle:needs review

#5573 Show diff for last selected file
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/ListViewExtensions.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/UserControls/FileStatusList.cs
Labels: status: ready, waffle:needs review

#5614 Fix #5605 Statistics plugin line stats broken
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  Plugins/Statistics/GitStatistics/FormGitStatistics.cs
Labels: waffle:needs review

#5597 Txt change: "Show in folder"
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormDiff.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/Translation/English.xlf
  GitUI/Translation/en_pseudo.xlf
Labels: waffle:ready

#5611 Update commit info panel layout
  GitUI/ColorHelper.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommitInfo/CommitInfo.Designer.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.Designer.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/CommitInfo/CommitInfoHeader.resx
  GitUI/GitUI.csproj
  GitUI/UserControls/BlameControl.cs
  GitUI/UserControls/DoubleBufferedTableLayoutPanel.cs
  ResourceManager/CommitDataRenders/CommitDataBodyRenderer.cs
  UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataBodyRendererTests.cs
Labels: area: user experience, type: feature request, waffle:ready

#5610 Create more scalable revision graph (performance)
  GitCommands/Git/GitRevision.cs
  GitCommands/RevisionReader.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/RevisionGrid/Columns/GraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/ActiveLaneRow.cs
  GitUI/UserControls/RevisionGrid/Graph/Edge.cs
  GitUI/UserControls/RevisionGrid/Graph/Edges.cs
  GitUI/UserControls/RevisionGrid/Graph/GraphModel.cs
  GitUI/UserControls/RevisionGrid/Graph/ILaneRow.cs
  GitUI/UserControls/RevisionGrid/Graph/Junction.cs
  GitUI/UserControls/RevisionGrid/Graph/JunctionColorProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/JunctionStyler.cs
  GitUI/UserControls/RevisionGrid/Graph/LaneInfo.cs
  GitUI/UserControls/RevisionGrid/Graph/LaneJunctionDetail.cs
  GitUI/UserControls/RevisionGrid/Graph/Node.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
  GitUI/UserControls/RevisionGrid/Graph/SavedLaneRow.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  GitUI/UserControls/RevisionGrid/VisibleRowRange.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/JunctionColorProviderTests.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/JunctionStylerTests.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: prio:high, status: needs review

#5637 Fix bug where long branch names overflow list view
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: waffle:needs review

#5631 Add default action for "Rename branch" context menu item when only one branch selected
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: waffle:needs review

#5645 #5642 fix performance issue when selecting large diff
  GitExtUtils/BinarySearch.cs
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/ListViewExtensions.cs
  GitUI/UserControls/ExListView.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/PathFormatter.cs
Labels: waffle:ready

#5655 Force commit info to clear on module change
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: waffle:needs review

#5651 Make GitExtensions project authority of GIT info
  GitExtensions/GitExtensions.csproj
  GitExtensions/Program.cs
  GitUI/GitUI.csproj
  GitUI/UserEnvironmentInformation.cs
  UnitTests/GitUITests/TranslationTest.cs
Labels: waffle:needs review

#5641 Fix commitInfo scroll on mouse wheel
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommitInfo/CommitInfo.Designer.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.Designer.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/MouseWheelRedirector.cs
Labels: waffle:needs review

#5628 Add script prefix for navigation in the revision grid
  GitUI/Script/ScriptRunner.cs
Labels: waffle:needs review

#5659 fix: Commit info context menu is scrambled
  GitUI/CommitInfo/CommitInfo.Designer.cs
Labels: waffle:ready

#5660 Enable RevisionDataGridView.DoubleBuffered
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: waffle:ready

#5662 fix: Saving command log to file broken
  GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
Labels: waffle:ready

#5661 Fix 5627 crash due to window positions.xml
  GitUI/GitExtensionsForm.cs
  GitUI/GitUI.csproj
  GitUI/WindowPositionManager.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/WindowPositionManagerTests.cs
Labels: waffle:ready

#5648 Split the reordering and rebuilding of the graph.
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: waffle:ready
