Repository gitextensions/gitextensions, pull requests merged in 2018-12, with the labels that each got.

#5835 Use stack instead of recursion in MakeRelative
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Labels: status: ready

#5841 Fix crash when open file with ".settings" extension
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: needs review

#5843 Fix crash when open project setting in Jira commit hint plugin
  Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
Labels: status: needs review

#5818 fix filter branch filter
  GitCommands/RevisionReader.cs
Labels: status: needs review

#5854 Use stack instead of recursion in EnsureScoreIsAbove
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Labels: status: ready

#5860 Added guard for EnsureScoreIsAbove.
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Labels: status: ready

#5871 Fix non-readonly commit message
  GitUI/CommitInfo/CommitInfo.Designer.cs
Labels: status: ready

#5865 Fix/search text box width
  GitUI/CommandsDialogs/SearchControl.Designer.cs
  GitUI/CommandsDialogs/SearchControl.cs
Labels: status: needs review

#5882 Fixes 5880: Reorder nodes correct
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
Labels: status: ready

#5894 Fix issue #5893
  Plugins/GitFlow/GitFlowForm.cs
Labels: status: needs review

#5878 Avoid blocking UI via WebClient.OpenReadTaskAsync
  GitUI/Avatars/AvatarDownloader.cs
  GitUI/UserControls/AvatarControl.cs
  Plugins/Gource/GourceStart.cs
Labels: status: ready

#5926 Browse: Sort the Plugin list in alphabetic order
  GitUI/CommandsDialogs/FormBrowse.cs
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Labels: status: ready

#5799 Revision Links: Detect GH issues without #
  GitExtensions.settings
Labels: status: ready

#5925 Help text for Edit .gitignore not wrapped
  GitUI/CommandsDialogs/FormGitIgnore.Designer.cs
Labels: status: ready

#5813 NullException comparing when no HEAD
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormReflog.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#5798 EditNetSpell: Don't open auto-complete when moving
  GitUI/SpellChecker/EditNetSpell.cs
Labels: type: discussion

#5938 Fixes: 5935. added saving left side splitter location in commit window
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: needs review

#5942 Fix incorrect resolution of {cDefaultRemotePathFromUrl} script variable
  GitUI/GitUI.csproj
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/Script/ScriptRunner.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
Labels: status: ready

#5941 AppVeyor settings enhancements
  GitUI/Translation/Czech.Plugins.xlf
  GitUI/Translation/Dutch.Plugins.xlf
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/French.Plugins.xlf
  GitUI/Translation/German.Plugins.xlf
  GitUI/Translation/Indonesian.Plugins.xlf
  GitUI/Translation/Italian.Plugins.xlf
  GitUI/Translation/Japanese.Plugins.xlf
  GitUI/Translation/Korean.Plugins.xlf
  GitUI/Translation/Polish.Plugins.xlf
  GitUI/Translation/Portuguese (Brazil).Plugins.xlf
  GitUI/Translation/Romanian.Plugins.xlf
  GitUI/Translation/Russian.Plugins.xlf
  GitUI/Translation/Simplified Chinese.Plugins.xlf
  GitUI/Translation/Spanish.Plugins.xlf
  GitUI/Translation/Traditional Chinese.Plugins.xlf
  Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.Designer.cs
Labels: status: needs review

#5952 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: ready

#5951 Console tab doesn't require translation strings
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#5887 Delete TryGetExactPath, to remove performance penalty
  GitCommands/PathUtil.cs
Labels: status: ready

#5964 Fix broken link
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
Labels: status: ready

#5680 Fix 5676 specify branch layout
  GitUI/GitUI.csproj
  GitUI/HelperDialogs/FormRunScriptSpecify.Designer.cs
  GitUI/HelperDialogs/FormRunScriptSpecify.cs
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/UserControls/RevisionGrid/FormQuickGitRefSelector.cs
  GitUI/UserControls/RevisionGrid/FormQuickItemSelector.Designer.cs
  GitUI/UserControls/RevisionGrid/FormQuickItemSelector.cs
  GitUI/UserControls/RevisionGrid/FormQuickItemSelector.resx
  GitUI/UserControls/RevisionGrid/FormQuickStringSelector.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
Labels: status: needs review

#5961 Fix scrolling index in PatchGrid for one skipped patch
  GitUI/UserControls/PatchGrid.cs
Labels: status: needs review

#5830 fix OverflowException on mousewheel with negative Cursor.Y
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/Win32ApiUtil.cs
  GitUI/MouseWheelRedirector.cs
  GitUI/UserControls/ExListView.cs
  UnitTests/GitExtUtils/GitExtUtilsTests.csproj
  UnitTests/GitExtUtils/Win32ApiTests.cs
Labels: status: needs review

#5930 Reenable vertical ruler
  GitCommands/Settings/AppSettings.cs
  GitUI/Editor/FileViewerInternal.Designer.cs
Labels: status: ready

#5900 Multiple Protocol Support for Cloning in ForkAndCloneForm
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  Plugins/GitHub3/GitHubRepo.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs
Labels: status: needs review

#5910 Prevent treeview scrolling during reload
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: status: needs review

#5838 Implement F3 to open difftool for .png
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Editor/FileViewer.cs
Labels: status: needs review

#5788 Update ManagedExtensibility to vs-mef
  GitExtensions/GitExtensions.csproj
  GitUI/Plugin/PluginRegistry.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
Labels: status: ready

#5897 QuickPull should behave the same as the default toolbar does.
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: needs review, type: bug

#5969 Close the Stash Manager on Esc keypress
  GitUI/CommandsDialogs/FormStash.cs
Labels: status: needs review

#5985 Fix empty commit detail and exception when reseting to a remote branch, complaining about the Commit Date < min UTC DateTime
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
Labels: status: needs review

#5993 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: status: needs review

#5996 Add missing test assemblies
  appveyor.yml
Labels: status: ready

#5997 Don't crash the app if unable to read settings
  GitCommands/Settings/FileSettingsCache.cs
Labels: status: ready

#6008 Fix tab order of Add Submodule form
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.Designer.cs
Labels: status: needs review

#5986 Fix 5197 highlight by author
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
  GitUI/UserControls/RevisionGrid/AuthorRevisionHighlighting.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/AuthorRevisionHighlightingTests.cs
Labels: status: ready

#5777 only update submodule status at changes
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
Labels: status: ready

#5991 Remove unused setting "Striped branch change"
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
Labels: status: ready
