Repository gitextensions/gitextensions, pull requests merged in 2018-04, with the labels that each got.

#4746 Cease checking if git-log output contains commitId - fixes #4745
  GitCommands/CommitDataManager.cs
Labels: ready

#4740 Start with dashboard also if started from valid Git repo
  GitExtensions/GitExtensions.csproj
  GitExtensions/Program.cs
Labels: ready

#4699 Fix commit drop downs (#4698)
  GitCommands/Git/GitDeleteBranchCmd.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Repository/RecentRepoInfo.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
  GitUI/UserControls/BlameControl.cs
Labels: ready

#4727 Prefer JoinableTaskFactory to other Invoke styles
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/FormProcess.cs
  GitUI/FormStatus.cs
  GitUI/UserControls/RevisionGrid.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/Bitbucket/BitbucketRequestBase.cs
  Plugins/FindLargeFiles/FindLargeFiles.csproj
  Plugins/FindLargeFiles/FindLargeFilesForm.cs
Labels: ready

#4755 fix: FormFixHome is messed up HiDPI
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.Designer.cs
Labels: visual hdpi

#4714 fix: FormRemotes is messed up on HiDPI
  GitUI/CommandsDialogs/FormRemotes.cs
Labels: visual hdpi

#4779 fix: FormRemotes is messed up on HiDPI
  GitUI/CommandsDialogs/FormRemotes.cs
Labels: visual hdpi

#4790 VSIX plugin: No icon for blame
  GitExtensionsVSIX/GitExtCommandTable.cs
  GitExtensionsVSIX/GitExtCommandTable.vsct
  GitExtensionsVSIX/Resources/Commands.png
Labels: VS plugin

#4772 Various high DPI fixes
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/ControlDpiExtensions.cs
  GitExtUtils/GitUI/DpiUtil.cs
  GitExtUtils/packages.config
  GitUI/BuildServerIntegration/BuildInfoDrawingLogic.cs
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  GitUI/CommandsDialogs/AboutBox.cs
  GitUI/CommandsDialogs/AboutBoxDialog/FormContributors.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.cs
  GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
  GitUI/CommandsDialogs/FormAddToGitIgnore.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDeleteBranch.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormPush.Designer.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormVerify.Designer.cs
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/FormViewPatch.Designer.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionFileTree.cs
  GitUI/CommandsDialogs/RevisionGpgInfo.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.Designer.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/Editor/FileViewer.cs
  GitUI/FormPuttyError.cs
  GitUI/FormStatus.cs
  GitUI/GitUI.csproj
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/PatchGrid.Designer.cs
  GitUI/UserControls/PatchGrid.cs
  GitUI/UserControls/RevisionGrid.Designer.cs
  GitUI/UserControls/RevisionGrid.cs
  GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  Plugins/FindLargeFiles/FindLargeFiles.csproj
  Plugins/FindLargeFiles/FindLargeFilesForm.Designer.cs
  Plugins/FindLargeFiles/FindLargeFilesForm.cs
  Plugins/GitFlow/GitFlow.csproj
  Plugins/GitFlow/GitFlowForm.cs
  Plugins/Statistics/GitStatistics/FormGitStatistics.cs
Labels: ready, visual hdpi

#4804 Use nameof for binding symbol members
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
  GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
  GitUI/CommandsDialogs/FormDeleteTag.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.Designer.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRebase.cs
  GitUI/CommandsDialogs/FormReflog.Designer.cs
  GitUI/CommandsDialogs/FormReflog.cs
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormSubmodules.Designer.cs
  GitUI/CommandsDialogs/FormSubmodules.cs
  GitUI/CommandsDialogs/FormVerify.Designer.cs
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/FormViewPatch.Designer.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.Designer.cs
  GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.Designer.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.Designer.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/HelperDialogs/FormSelectMultipleBranches.cs
  GitUI/SpellChecker/EditNetSpell.Designer.cs
  GitUI/SpellChecker/EditNetSpell.cs
  GitUI/UserControls/BranchComboBox.cs
  GitUI/UserControls/PatchGrid.Designer.cs
  GitUI/UserControls/PatchGrid.cs
  GitUI/UserControls/RevisionGridClasses/FormQuickGitRefSelector.Designer.cs
  GitUI/UserControls/RevisionGridClasses/FormQuickGitRefSelector.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.Designer.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  Plugins/FindLargeFiles/FindLargeFilesForm.Designer.cs
  Plugins/FindLargeFiles/FindLargeFilesForm.cs
  TranslationApp/FormTranslate.Designer.cs
  TranslationApp/FormTranslate.cs
Labels: ready

#4807 Show FormDiff modeless.
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/GitUICommands.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/RevisionGrid.cs
Labels: feature request

#4531 Issue 4453
  GitCommands/Remote/GitRemoteManager.cs
  GitCommands/StringExtensions.cs
  UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs
  UnitTests/GitCommandsTests/StringExtensionTests.cs
Labels: needs review

#4840 Disable ROT panel while loading.
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: feature request, left-panel

#4841 Reload ROT only when visible.
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: feature request, left-panel

#4851 Improve build result rendering
  GitUI/BuildServerIntegration/BuildInfoDrawingLogic.cs
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/Resources/Icons/BuildCancelled.png
  GitUI/Resources/Icons/BuildFailed.png
  GitUI/Resources/Icons/BuildSuccessful.png
  GitUI/UserControls/RevisionGrid.cs
Labels: UX, visual hdpi

#4872 Fix RepoObjectsTree icon sizes at high DPI
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: visual hdpi
