Repository gitextensions/gitextensions, pull requests merged in 2018-03, with the labels that each got.

#4526 Delete TAGMESSAGE after tag command completes
  GitCommands/Git/Tag/GitTagController.cs
  GitUI/CommandsDialogs/FormCreateTag.cs
  GitUI/CommandsDialogs/FormVerify.cs
  UnitTests/GitCommandsTests/Git/Tag/GitTagControllerTest.cs
Labels: needs review

#4552 Await for diff being loaded.
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/FindAndReplaceForm.cs
  GitUI/Editor/IFileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/FileStatusList.cs
Labels: ready

#4551 Enable SA0001 (XML documentation validation)
  Directory.Build.props
  FxCop.targets
  FxCopRules.ruleset
  GitCommands/Git/GitModule.cs
  GitCommands/GitCommands.csproj
  GitCommands/Remote/GitRemote.cs
  GitExtUtils/GitExtUtils.csproj
  GitExtensions.ruleset
  GitExtensions.sln
  GitExtensions/GitExtensions.csproj
  GitExtensionsVSIX/GitExtensionsVSIX.csproj
  GitPlugin/GitPlugin.csproj
  GitPluginShared/GitPluginShared.csproj
  GitUI/GitUI.csproj
  GitUI/UserControls/RevisionGridClasses/DvcsGraph.Designer.cs
  Gravatar/DefaultImageType.cs
  Gravatar/Gravatar.csproj
  NetSpell.SpellChecker/SpellChecker.csproj
  NetSpell.SpellChecker/Spelling.cs
  Plugins/AutoCompileSubmodules/AutoCompileSubmodules.csproj
  Plugins/BackgroundFetch/BackgroundFetch.csproj
  Plugins/Bitbucket/Bitbucket.csproj
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj
  Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsIntegration.csproj
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityIntegration.csproj
  Plugins/BuildServerIntegration/TfsIntegration/TfsIntegration.csproj
  Plugins/BuildServerIntegration/TfsInterop.Vs2012/TfsInterop.Vs2012.csproj
  Plugins/BuildServerIntegration/TfsInterop.Vs2013/TfsInterop.Vs2013.csproj
  Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
  Plugins/CreateLocalBranches/CreateLocalBranches.csproj
  Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj
  Plugins/FindLargeFiles/FindLargeFiles.csproj
  Plugins/Gerrit/Gerrit.csproj
  Plugins/GitFlow/GitFlow.csproj
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/ISetting.cs
  Plugins/Github3/Github3.csproj
  Plugins/Gource/Gource.csproj
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj
  Plugins/ProxySwitcher/ProxySwitcher.csproj
  Plugins/ReleaseNotesGenerator/ReleaseNotesGenerator.csproj
  Plugins/Statistics/GitImpact/GitImpact.csproj
  Plugins/Statistics/GitStatistics/GitStatistics.csproj
  ResourceManager/LocalizationHelpers.cs
  ResourceManager/ResourceManager.csproj
  TranslationApp/TranslationApp.csproj
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GravatarTests/GravatarTests.csproj
  UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj
  UnitTests/ResourceManagerTests/ResourceManagerTests.csproj
Labels: ready

#4557 Reset folder in file tree regression in 2.51
  GitUI/CommandsDialogs/RevisionFileTree.cs
Labels: ready

#4572 Handle OperationCanceledException.
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/Editor/FindAndReplaceForm.cs
Labels: ready

#4585 Diff for initial commit of a file were presented as a diff to local
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/HelperDialogs/FormCommitDiff.cs
Labels: ready

#4554 Commit info in history form
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/GitUI.csproj
  GitUI/HelperDialogs/FormCommitDiff.Designer.cs
  GitUI/HelperDialogs/FormCommitDiff.cs
  GitUI/UserControls/CommitDiff.Designer.cs
  GitUI/UserControls/CommitDiff.cs
  GitUI/UserControls/CommitDiff.resx
Labels: ready

#4608 Sort branches/tags in the revision grid with current branch first in …
  GitUI/UserControls/RevisionGrid.cs
Labels: ready

#4280 Support build integration support for variables
  GitCommands/GitCommands.csproj
  GitCommands/Remote/RepoNameExtractor.cs
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
  Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs
  Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerWatcher.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/RepoNameExtractorTest.cs
Labels: ready

#4605 Fix issue that excess rebase command being performed when continue rebase
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/MergeConflictHandler.cs
  GitUI/GitUICommands.cs
Labels: ready

#4598 Issue 2838
  Plugins/GitFlow/GitFlowForm.cs
Labels: ready

#4247 Activate artificial commits by default #4033
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid.cs
  ResourceManager/Strings.cs
Labels: ready

#4652 Difference for initial commit of a file were presented as a diff to the working directory
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/HelperDialogs/FormCommitDiff.cs
Labels: high priority

#4671 Linq tweaks
  GitCommands/Config/ConfigFile.cs
  GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Patch/Patch.cs
  GitCommands/Repository/RecentRepoInfo.cs
  GitCommands/Repository/Repositories.cs
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiff.cs
  GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/Editor/FileViewer.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid.cs
  GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
  Plugins/Statistics/GitStatistics/LineCounter.cs
  Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
  Plugins/Statistics/GitStatistics/PieChart/PieChartControl.cs
  TranslationApp/FormTranslate.cs
  UnitTests/GitUITests/Editor/Diff/LinePrefixHelperFixture.cs
Labels: ready

#4677 Use C# 7 deconstruction
  GitCommands/BoolExtensions.cs
  GitCommands/Config/ConfigFile.cs
  GitCommands/DeconstructionExtensions.cs
  GitCommands/GitCommands.csproj
  GitCommands/Settings/SettingsCache.cs
  GitCommands/Statistics/ImpactLoader.cs
  GitCommands/StringExtensions.cs
  GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
  GitUI/UserControls/ConsoleEmulatorOutputControl.cs
  GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid.cs
  Plugins/Statistics/GitImpact/ImpactControl.cs
  Plugins/Statistics/GitStatistics/FormGitStatistics.cs
  ResourceManager/Xliff/TranslationUtl.cs
  TranslationApp/FormTranslate.cs
  TranslationApp/Program.cs
  TranslationApp/TranslationHelpers.cs
  UnitTests/GitUITests/TranslationTest.cs
Labels: ready

#4658 Remove SVN support
  GitCommands/Git/GitSvnCommandHelpers.cs
  GitCommands/GitCommands.csproj
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormSvnClone.Designer.cs
  GitUI/CommandsDialogs/FormSvnClone.cs
  GitUI/CommandsDialogs/FormSvnClone.resx
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  GitUI/MessageBoxes.cs
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/Resources/Icons/IconCloneRepoSvn.png
  Plugins/GitUIPluginInterfaces/IGitUICommands.cs
Labels: ready

#4672 Ternary conditionals
  GitCommands/Config/ConfigFile.cs
  GitCommands/Config/ConfigSection.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/SettingsCache.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/CommandsDialogs/FormCreateBranch.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFormatPatch.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
  GitUI/FormStatus.cs
  GitUI/GitUICommands.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/Script/SplitButton.cs
  GitUI/SpellChecker/EditNetSpell.cs
  GitUI/UserControls/BlameControl.cs
  GitUI/UserControls/BranchSelector.cs
  GitUI/UserControls/HelpImageDisplayUserControl.cs
  GitUI/UserControls/RevisionGrid.cs
  Plugins/GitUIPluginInterfaces/Settings/BoolSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/ChoiceSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/PasswordSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
  Plugins/ProxySwitcher/ProxySwitcherForm.cs
  ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs
  ResourceManager/LinkFactory.cs
Labels: ready

#4681 Replace tail call recursion with loop
  GitUI/GitUIExtensions.cs
  GitUI/Plugin/LoadPlugins.cs
Labels: ready

#4705 Get remotes
  GitCommands/Git/GitModule.cs
  GitCommands/Remote/GitRemoteManager.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
Labels: ready

#4706 Make GitStash immutable and use regex parsing
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitStash.cs
  GitUI/CommandsDialogs/FormStash.cs
  UnitTests/GitCommandsTests/Git/GitStashTests.cs
Labels: ready

#4707 Review GitModule.GetSelectedBranchFast
  GitCommands/Git/GitModule.cs
Labels: ready

#4695 Add missing word to dialog text (#4691)
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiff.cs
Labels: bug

#4711 Fix avatar under high DPI
  GitUI/DpiUtil.cs
  GitUI/GitExtensionsForm.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/GravatarControl.cs
  ResourceManager/GitExtensionsUserControl.cs
Labels: ready, visual hdpi

#4697 Patches 3/3
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/IndexLockManager.cs
  GitCommands/GitCommands.csproj
  GitCommands/Patch/Patch.cs
  GitCommands/Patch/PatchProcessor.cs
  GitCommands/Patches/Patch.cs
  GitCommands/Patches/PatchFile.cs
  GitCommands/Patches/PatchManager.cs
  GitCommands/Patches/PatchProcessor.cs
  GitCommands/Utils/EncodingHelper.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormViewPatch.Designer.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/Editor/Diff/DiffHighlightService.cs
  GitUI/Editor/Diff/DiffLineNumAnalyzer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/IFileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/PatchGrid.Designer.cs
  GitUI/UserControls/PatchGrid.cs
  ResourceManager/LocalizationHelpers.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/GitModuleTest.cs
  UnitTests/GitCommandsTests/Patch/PatchManagerTest.cs
  UnitTests/GitCommandsTests/Patch/PatchTest.cs
  UnitTests/GitCommandsTests/Patches/PatchProcessorTest.cs
  UnitTests/GitCommandsTests/Patches/PatchTest.cs
  UnitTests/GitCommandsTests/Patches/testdata/big.patch
  UnitTests/GitCommandsTests/Patches/testdata/bigBin.patch
  UnitTests/GitCommandsTests/Patches/testdata/rebase.diff
Labels: ready
