Repository gitextensions/gitextensions, pull requests merged in 2018-05, with the labels that each got.

#4899 Migrate categorised local repositories
  GitCommands/GitCommands.csproj
  GitCommands/UserRepositoryHistory/IRepositoryManager.cs
  GitCommands/UserRepositoryHistory/IRepositorySerialiser.cs
  GitCommands/UserRepositoryHistory/Legacy/Repository.cs
  GitCommands/UserRepositoryHistory/Legacy/RepositoryCategory.cs
  GitCommands/UserRepositoryHistory/Legacy/RepositoryCategoryXmlSerialiser.cs
  GitCommands/UserRepositoryHistory/Legacy/RepositoryHistoryMigrator.cs
  GitCommands/UserRepositoryHistory/Legacy/RepositoryHistorySurrogate.cs
  GitCommands/UserRepositoryHistory/Legacy/RepositoryStorage.cs
  GitCommands/UserRepositoryHistory/LocalRepositoryManager.cs
  GitCommands/UserRepositoryHistory/RemoteRepositoryManager.cs
  GitCommands/UserRepositoryHistory/RepositoryHistoryManager.cs
  GitCommands/UserRepositoryHistory/RepositoryStorage.cs
  GitCommands/UserRepositoryHistory/RepositoryXmlSerialiser.cs
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
  GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormBrowse.resx
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/MockData/CategorisedRepositories01.xml
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/MockData/CategorisedRepositories02.xml
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/RepositoryCategorySerialiserTests.Verify_backwards_compatibility_of_object_graph.approved.xml
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/RepositoryCategoryXmlSerialiserTests.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/RepositoryHistoryMigratorTests.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/RepositoryStorageTests.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/LocalRepositoryManagerTests.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/RemoteRepositoryManagerTests.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/RepositoriesTests.Deserialize_recent_repositories.approved.txt
  UnitTests/GitCommandsTests/UserRepositoryHistory/RepositoriesTests.Deserialize_remote_repositories.approved.txt
  UnitTests/GitCommandsTests/UserRepositoryHistory/RepositoriesTests.Serialize_recent_repositories.approved.xml
  UnitTests/GitCommandsTests/UserRepositoryHistory/RepositoriesTests.Serialize_remote_repositories.approved.xml
  UnitTests/GitCommandsTests/UserRepositoryHistory/RepositoryStorageTests.cs
Labels: feature request

#4927 fix Git config diff.noprefix true option breaks most of GitExtensions functionality
  GitCommands/Git/GitModule.cs
Labels: ready

#4799 Remove the old Visual Studio addin project (GitPlugin)
  GitExtensions.sln
  GitPlugin/CommandBar.resx
  GitPlugin/Connect.cs
  GitPlugin/GitPlugin.AddIn
  GitPlugin/GitPlugin.csproj
  GitPlugin/GitPluginKey.pfx
  GitPlugin/Plugin.cs
  GitPlugin/Properties/AssemblyInfo.cs
  GitPlugin/Properties/DataSources/GitCommands.GitItem.datasource
  GitPlugin/Properties/DataSources/GitCommands.GitRevision.datasource
  GitPlugin/Properties/Resources.Designer.cs
  GitPlugin/Properties/Resources.resx
  GitPlugin/Resources/13.bmp
  GitPlugin/Resources/14.bmp
  GitPlugin/Resources/7.bmp
  GitPlugin/Resources/8.bmp
  GitPlugin/Resources/9.bmp
  GitPlugin/Resources/AboutBox.bmp
  GitPlugin/Resources/Bash.bmp
  GitPlugin/Resources/Configure.bmp
  GitPlugin/Resources/Edit.bmp
  GitPlugin/Resources/EditAll.bmp
  GitPlugin/Resources/IconBranchCheckout.bmp
  GitPlugin/Resources/IconBranchCheckout.png
  GitPlugin/Resources/IconBranchCreate.bmp
  GitPlugin/Resources/IconBranchCreate.png
  GitPlugin/Resources/IconBrowseFileExplorer.bmp
  GitPlugin/Resources/IconBrowseFileExplorer.png
  GitPlugin/Resources/IconCherryPick.bmp
  GitPlugin/Resources/IconCherryPick.png
  GitPlugin/Resources/IconCloneRepoGit.bmp
  GitPlugin/Resources/IconCloneRepoGit.png
  GitPlugin/Resources/IconDiff.bmp
  GitPlugin/Resources/IconEditGitIgnore.bmp
  GitPlugin/Resources/IconEditGitIgnore.png
  GitPlugin/Resources/IconFind.bmp
  GitPlugin/Resources/IconFind.png
  GitPlugin/Resources/IconManageRemotes.bmp
  GitPlugin/Resources/IconManageRemotes.png
  GitPlugin/Resources/IconMerge.bmp
  GitPlugin/Resources/IconMerge.png
  GitPlugin/Resources/IconRebase.bmp
  GitPlugin/Resources/IconRebase.png
  GitPlugin/Resources/IconResetFileChanges.bmp
  GitPlugin/Resources/IconResetFileChanges.png
  GitPlugin/Resources/IconResetWorkingDirChanges.png
  GitPlugin/Resources/Revert.bmp
  GitPlugin/Resources/RevisionHistory.bmp
  GitPlugin/Resources/Stash.bmp
  GitPlugin/Resources/_Howto_Create_bmp_Icons.txt
  GitPlugin/_Test_Install_Plugin.cmd
  GitPlugin/_Test_Open_PluginDir.cmd
  GitPlugin/_Test_Remove_Plugin.cmd
  GitPlugin/_Test_ResetAddin.cmd
  GitPlugin/app.config
  README.md
  Setup/Product.wxs
  Setup/RemoveVSAddInCommands.vbs
Labels: ready

#4932 Check for recommended Git version 2.51
  GitCommands/Git/GitVersion.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
  GitUI/Translation/Czech.xlf
  GitUI/Translation/Dutch.xlf
  GitUI/Translation/English.xlf
  GitUI/Translation/French.xlf
  GitUI/Translation/German.xlf
  GitUI/Translation/Italian.xlf
  GitUI/Translation/Japanese.xlf
  GitUI/Translation/Korean.xlf
  GitUI/Translation/Polish.xlf
  GitUI/Translation/Portuguese (Brazil).xlf
  GitUI/Translation/Portuguese (Portugal).xlf
  GitUI/Translation/Romanian.xlf
  GitUI/Translation/Russian.xlf
  GitUI/Translation/Simplified Chinese.xlf
  GitUI/Translation/Spanish.xlf
  GitUI/Translation/Traditional Chinese.xlf
  GitUI/Translation/en_pseudo.Plugins.xlf
  GitUI/Translation/en_pseudo.xlf
Labels: ready

#4933 Remove Git and KDiff3 from installer 2.51
  .gitignore
  GitExtensions.VS2015.sln
  Setup/BuildGitExtNative.cmd
  Setup/BuildInstallers.VS2015.cmd
  Setup/BuildInstallers.VS2017.cmd
  Setup/DownloadExternals.cmd
  Setup/MakeInstallers.cmd
  Setup/Product.wxs
  Setup/README.md
  Setup/Setup.wixproj
  Setup/UI/RequiredSoftwareDlg.wxs
  Setup/UI/WixUI.wxs
  Setup/hMSBuild.bat
  Setup/tools/curl.exe
  appveyor.yml
Labels: ready

#3693 feat: Dashboard revisited
  GitCommands/UserRepositoryHistory/LocalRepositoryManager.cs
  GitExtUtils/GitUI/DpiUtil.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.resx
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.resx
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardTheme.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/FormDashboardCategoryTitle.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/FormDashboardCategoryTitle.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/FormDashboardCategoryTitle.resx
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/RepositoryEventArgs.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.resx
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Editor/ColorHelper.cs
  GitUI/GitUI.csproj
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/Properties/Settings.Designer.cs
  GitUI/Resources/Icons/14_bw.png
  GitUI/Resources/Icons/bgblue.png
  GitUI/Resources/Icons/bggrey.png
  GitUI/Resources/Icons/bullet_add.png
  GitUI/Resources/Icons/bullet_delete.png
  GitUI/Resources/Icons/folder_error.png
  GitUI/Resources/Icons/folder_git.png
  GitUI/Resources/Icons/git_extensions_logo.png
  GitUI/Resources/Icons/originals/_Icon Sources.txt
  GitUI/Resources/Icons/x_with_arrow_32.png
  GitUI/Translation/English.xlf
  Plugins/Gerrit/GerritPlugin.cs
  UnitTests/GitCommandsTests/UserRepositoryHistory/LocalRepositoryManagerTests.cs
Labels: dashboard

#4962 Handle start with dashboard explicitly
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUICommands.cs
Labels: ready

#4965 fix: Crash when you click on the Commit tab
  GitCommands/CommitData.cs
  GitCommands/System.cs
Labels: info needed

#4809 Editor syntax highlighting for commit and interactive rebase
  GitCommands/Git/GitDirectoryResolver.cs
  GitUI/CommandsDialogs/FormEditor.cs
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
  GitUI/Editor/CommitMessageHighlightingStrategy.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/GitHighlightingStrategyBase.cs
  GitUI/Editor/IFileViewer.cs
  GitUI/Editor/RebaseTodoHighlightingStrategy.cs
  GitUI/GitModuleForm.cs
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  ResourceManager/GitExtensionsFormBase.cs
Labels: UX, needs review
