Repository gitextensions/gitextensions, pull requests merged in 2018-06, with the labels that each got.

#5020 Fix 4830 inconsistent branch ordering
  GitCommands/Git/GitModule.cs
  GitCommands/GitCommands.csproj
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/BranchOrdering.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ToolbarSettingsPage.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
  Plugins/GitUIPluginInterfaces/GitRefsOrder.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/IGitModule.cs
Labels: left-panel

#5019 Remove 'Force Delete' functionality
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
Labels: left-panel

#5012 Left panel tweaks
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/BranchTreePanel/RepoObjectsTree.resx
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUI.csproj
Labels: left-panel

#5041 fix: Windows size not restored
  GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
  GitUI/CommandsDialogs/FormCleanupRepository.cs
  GitUI/GitExtensionsForm.cs
Labels: ready

#5060 Nullexception when no submodule status
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormDiff.cs
Labels: regression

#5077 Show branches before tags in the revision grid.
  GitUI/UserControls/RevisionGrid.cs
Labels: ready

#5037 Change some default settings values
  GitCommands/Settings/AppSettings.cs
Labels: ready

#5045 Apply font setting when using git commit template
  GitUI/CommandsDialogs/FormCommit.cs
Labels: ready

#5097 Better accessibility for reset dialog
  GitUI/CommandsDialogs/FormResetChanges.Designer.cs
Labels: user experience

#4559 Option to always show rebase dialog
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs
  GitUI/GitUICommands.cs
Labels: needs review
