Repository gitextensions/gitextensions, pull requests merged in 2018-09, with the labels that each got.

#5357 fix: Prevent LeftPanel from changing commit selection
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: area: left-panel

#5412 FormPull: Set fetch as default
  GitUI/CommandsDialogs/FormPull.cs
Labels: status: ready

#5425 GoToSuperproject and GoToSubmodule hotkeys
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
Labels: type: feature request

#5398 Use monospace font for Commit Id column
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/RevisionGrid/CellStyle.cs
  GitUI/UserControls/RevisionGrid/Columns/AuthorNameColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/GraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#5450 Fix broken revision grid content filter
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: type: bug

#5475 StagedStatus.Unknown is an invalid status.
  GitCommands/Git/GitCommandHelpers.cs
Labels: type: bug, type: regression

#5476 Resolve DIR properly when gitext.sh is symlinked on Linux
  Bin/gitext.sh
Labels: area: linux/mono
