Repository gitextensions/gitextensions, pull requests merged in 2019-08, with the labels that each got.

#6952 Add "default pull action" config in setting dialog
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: status: cla signed

#6272 Add codescene.io analysis results
  README.md
Labels: status: cla signed, status: needs review

#6954 Fix/search unmerged branches
  GitExtensions.sln
  Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs
  UnitTests/Plugins/DeleteUnusedBranchesTests/DeleteUnusedBranchesTests.csproj
  UnitTests/Plugins/DeleteUnusedBranchesTests/GitBranchOutputCommandParserTests.cs
  UnitTests/Plugins/DeleteUnusedBranchesTests/Properties/AssemblyInfo.cs
Labels: status: cla signed

#7003 Fix: Commit Dialog Spell Checker
  GitUI/SpellChecker/TextBoxHelper.cs
Labels: status: cla signed

#7002 Fix: Proper spacing
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/Translation/English.xlf
Labels: status: cla signed

#7021 Fix for issue #7020. The GroupBox items contained in the form need to…
  GitUI/CommandsDialogs/FormPull.Designer.cs
  contributors.txt
Labels: status: cla signed

#7012 should fix: [NBug] Sequence contains no elements #7011
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  contributors.txt
Labels: status: cla signed

#7033 Open jira settings when not configured
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Labels: type: bug

#7053 fix: Overflow error in Commit Dialog
  GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
Labels: status: needs cla
