Repository gitextensions/gitextensions, pull requests merged in 2019-02, with the labels that each got.

#6196 fix build server settings page that could be clipped
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs
Labels: status: cla signed, status: ready

#6187 Toggle autocomplete commit textbox
  GitUI/SpellChecker/EditNetSpell.cs
Labels: status: ready

#6204 Fix tests hang
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/UserControls/AvatarControl.Designer.cs
  GitUI/UserControls/AvatarControl.cs
Labels: status: ready

#6202 FormCommit no longer show the committer info
  GitUI/CommandsDialogs/FormCommit.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Labels: status: ready

#6207 Update local translations
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Translation/English.xlf
Labels: status: ready

#6195 Cleanup GitModule
  GitCommands/CommitDataManager.cs
  GitCommands/FileHelper.cs
  GitCommands/Git/ConflictData.cs
  GitCommands/Git/ConflictedFileData.cs
  GitCommands/Git/Executable.cs
  GitCommands/Git/ForcePushOptions.cs
  GitCommands/Git/GitCommandRunner.cs
  GitCommands/Git/GitGpgController.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitModuleEventArgs.cs
  GitCommands/Git/GitSubmoduleStatus.cs
  GitCommands/Git/SubmoduleStatus.cs
  GitCommands/Git/SystemEncodingReader.cs
  GitCommands/GitCommands.csproj
  GitCommands/RevisionReader.cs
  GitCommands/Statistics/ImpactLoader.cs
  GitCommands/Submodules/DetailedSubmoduleInfo.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/CommandsDialogs/FormMergeSubmodule.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormReflog.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/FormVerify.LostObject.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUICommands.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
  Plugins/CreateLocalBranches/CreateLocalBranchesForm.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  Plugins/FindLargeFiles/FindLargeFilesForm.cs
  Plugins/Gerrit/GerritUtil.cs
  Plugins/GitFlow/GitFlowForm.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/IExecutable.cs
  Plugins/GitUIPluginInterfaces/IGitCommandRunner.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  Plugins/Gource/GourceStart.cs
  Plugins/ProxySwitcher/ProxySwitcherForm.cs
  Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs
  ResourceManager/LocalizationHelpers.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/GitCommandsTests/Config/ConfigFileTest.cs
  UnitTests/GitCommandsTests/Git/GitDescribeProviderTests.cs
  UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
  UnitTests/GitCommandsTests/MockExecutable.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Labels: status: ready

#6215 Fixes 6210: support single detached commits without segment
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: status: ready

#6216 Fixes 6193: ArgumentOutOfRangeException could occur in graph
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: status: ready

#6173 Toggle visibility of refs in the left panel
  GitCommands/Settings/AppSettings.cs
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/GitUI.csproj
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/DocumentTree.png
Labels: status: ready

#6222 Sign off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: needs review

#6227 fix: Unable to delete favourited repository
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: status: ready

#6228 fix missing dashboard highlighting on right click
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: status: ready

#6186 SubmoduleStatusProvider always sets TopProject
  GitCommands/Submodules/SubmoduleInfoResult.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
Labels: status: ready

#6233 Glen Nicol signed contributors.txt
  contributors.txt
Labels: status: needs review

#6230 Mark all files that we inject version number into as clean
  Setup/Mark-RepoClean.ps1
  appveyor.yml
Labels: status: ready

#6232 Show fixed shortcuts in context menu, too
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Labels: status: needs review

#5776 Issue 3320 - Plugin registration phase
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUICommands.cs
  GitUI/Plugin/PluginRegistry.cs
  TranslationApp/Program.cs
Labels: status: cla signed, status: ready

#6229 Standardize revision grid context menu
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Labels: status: needs review

#6234 #4826: Commit form should have a selection whenever possible
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: cla signed, status: needs review

#6224 Left panel: disable OnSelected when using arrow keys to navigate node…
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
Labels: status: ready

#6238 fix: QuickPull menu hotkey not working
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#6242 Set the title of the ColorsSettingsPage
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
Labels: status: needs review

#6248 #6246: NullReferenceException in commit dialog
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
Labels: status: needs review

#6199 Show remote branch in Commit dialog
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/GitUICommands.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Labels: status: cla signed, status: needs review

#6258 Sign developer certifciate of origin
  contributors.txt
Labels: status: needs review

#6259 Signed off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: needs review

#6261 Fix unit test that fails only on CI server
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Labels: status: needs review

#6262 Update contributors.txt
  contributors.txt
Labels: status: needs review

#6257 README: Improve download links
  README.md
Labels: status: cla signed, status: needs review

#6264 Tests: run tests in their own repositories
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Labels: status: needs review

#6255 Dashboard: Add ability to drag and drop a folder from Windows explorer to UserRe…
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: status: cla signed, status: ready

#6245 Fix resizing of revision grid columns
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: cla signed, status: needs review

#6129 Fix CodeCov coverage - exclude unit test files
  appveyor.yml
  codecov.yml
Labels: status: cla signed, status: needs review

#6219 Skip grid refresh after running a navigational script
  GitCommands/CommandStatus.cs
  GitCommands/GitCommands.csproj
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitModuleControl.cs
  GitUI/GitModuleForm.cs
  GitUI/Script/ScriptManager.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  ResourceManager/GitExtensionsControl.cs
  ResourceManager/GitExtensionsFormBase.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Labels: status: cla signed, status: needs review

#6280 Existing branch combobox could be empty
  GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
Labels: status: needs review

#6250 FormCleanupRepository: Add a button to easily add a path to clean up
  GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
  GitUI/CommandsDialogs/FormCleanupRepository.cs
Labels: status: cla signed, status: needs review

#6249 FormBrowse: Add support of drag and drop of a file that select it in …
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeController.cs
  UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs
Labels: status: cla signed, status: ready

#6211 Remove .vsix from Wix installer
  Setup/Product.wxs
  appveyor.yml
Labels: status: ready

#6287 Don't load avatars, if network is not available
  GitUI/Avatars/AvatarDownloader.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.resx
  GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
  GitUI/GitUI.csproj
  GitUI/Native.cs
Labels: status: ready

#6293 Move prune/prune all/update in Leftpanel remotes contextual menu
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/CommandsDialogs/FormRemotes.cs
Labels: status: cla signed, status: ready

#6303 GitExtensions -> Git Extensions
  CONTRIBUTING.md
  GitCommands/Git/SystemEncodingReader.cs
  GitExtUtils/ClipboardUtil.cs
  GitExtensions.ruleset
  GitExtensions/Program.cs
  GitExtensionsVSIX/Git/GitCommands.cs
  GitUI/Avatars/AvatarDownloader.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/FormRemoteProcess.cs
  Plugins/Gerrit/FormPluginInformation.resx
  contributors.txt
Labels: status: cla signed, status: needs review

#6312 Add support for Robohash no image service
  GitCommands/Settings/DefaultImageType.cs
  GitUI/Avatars/AvatarDownloader.cs
  contributors.txt
Labels: status: needs review

#6309 Improve GitHub integration
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.Designer.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  Plugins/GitHub3/GitHubPullRequest.cs
  Plugins/GitHub3/GitHubPullRequestDiscussion.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/IPullRequestInformation.cs
Labels: status: needs review

#6317 Add contributor information
  contributors.txt
Labels: status: needs review

#5050 fix "Remote repositories" popup for high dpi UI
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/CommandsDialogs/FormRemotes.cs
Labels: status: needs review

#6323 Fix flaky form commit tests
  GitUI/CommandsDialogs/FormCommit.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
  UnitTests/GitUITests/UITest.cs
Labels: status: ready
