Repository gitextensions/gitextensions, pull requests merged in 2019-04, with the labels that each got.

#6428 Updated links to git-scm.com
  GitCommands/Git/GitModule.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
Labels: area: documentation, status: ready

#6401 Fix fileviewer ShowLineNumbers setting that was not honored
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/IFileViewer.cs
Labels: status: cla signed, status: ready

#6372 Serialize submodules info loading
  GitCommands/Git/ExecutableExtensions.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormMergeSubmodule.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/Editor/FileViewer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: ready

#6394 #6147 inverted diffs after refresh
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: cla signed, status: ready

#6433 Refactor: simplified some methods in the TestAccessor
  GitUI/Editor/FileViewer.cs
Labels: status: needs review

#6366 Avoid freeze when staging many files at once (works only when AppSettings.ShowErrorsWhenStagingFiles==false)
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: ready

#6439 fix #6438
  GitUI/CommandsDialogs/FormResolveConflicts.cs
Labels: status: needs review

#6444 Detailed submodule status in dropdown menu was not updated
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready, type: regression

#6453 fix #6375 ExListView not custom drawing after collapse / expand group
  GitUI/UserControls/ExListView.cs
Labels: status: needs review

#6448 Mention regex in label of FileStatusList's filter
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.Designer.cs
Labels: status: needs review

#6451 Detect and display Git warning on broken refs
  GitCommands/Git/GitException.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/RefsWarningException.cs
  GitCommands/GitCommands.csproj
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6464 fix: JiraCommitHintPlugin hidpi layout issues
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Labels: status: ready

#6462 Add tests for GitModule.GetSortedRefs()
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: needs review

#6469 Fix Git arguments for formatting multiple patches
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: needs review

#6332 fix: Thread exhaustion by commit info data load
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6467 feat: JiraCommitHintPlugin credentials secure store
  GitCommands/ExternalLinks/ConfiguredLinkDefinitionsProvider.cs
  GitCommands/ExternalLinks/ExternalLinksManager.cs
  GitCommands/ExternalLinks/ExternalLinksStorage.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/ConfigFileSettings.cs
  GitCommands/Settings/MemorySettings.cs
  GitCommands/Settings/RepoDistSettings.cs
  GitCommands/Settings/SettingsContainer.cs
  GitExtUtils/GitExtUtils.csproj
  GitExtensions.sln
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/ConfigFileSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Plugins/PluginRootIntroductionPage.cs
  GitUI/CommandsDialogs/SettingsDialog/RepoDistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
  GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs
  GitUI/Plugin/GitPluginSettingsContainer.cs
  Plugins/GitUIPluginInterfaces/CredentialsManager.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/ISetting.cs
  Plugins/GitUIPluginInterfaces/ISettingControlBinding.cs
  Plugins/GitUIPluginInterfaces/ISettingsSource.cs
  Plugins/GitUIPluginInterfaces/SettingLevel.cs
  Plugins/GitUIPluginInterfaces/Settings/BoolSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/ChoiceSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/CredentialsSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/PasswordSetting.cs
  Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
  Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.Designer.cs
  Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.cs
  Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.resx
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
  Setup/MakePortableArchive.cmd
  Setup/Product.wxs
  UnitTests/GitCommandsTests/ExternalLinks/ConfiguredLinkDefinitionsProviderTests.cs
  UnitTests/GitCommandsTests/ExternalLinks/ExternalLinksManagerIntegrationTests.cs
  UnitTests/GitCommandsTests/ExternalLinks/ExternalLinksStorageIntegrationTests.cs
Labels: status: ready

#6466 Highlight the new name in the FileStatusList
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/PathFormatter.cs
  UnitTests/GitUITests/CommandsDialogs/PathFormatterTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: needs review

#6450 Clarify quick search by adding a prefix
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/QuickSearchProvider.cs
  ResourceManager/Strings.cs
Labels: status: needs review

#6474 fix: Application crashes when selecting "Go to commit" and having big contents in clipboard
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6475 Add tests follow up on #6474
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6476 fix: Console tab setting requires restart
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
Labels: status: ready

#6477 fix: This repository does not yet contain any commits
  GitCommands/Git/GitModule.cs
  GitCommands/PathUtil.cs
  UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Labels: status: ready

#6479 Clear diff in history form when no file selected
  GitUI/UserControls/CommitDiff.cs
Labels: status: needs review

#6488 TestHelper used GitExecutable for superproject
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
Labels: status: ready

#6490 Remove executable arg for GitModule
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6482 Hotkeys for Open with difftool | First/Selected to working directory
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
Labels: status: ready

#6492 Fix freezing when staging many files with autocrlf
  GitCommands/Git/ExecutableExtensions.cs
  contributors.txt
Labels: status: ready

#6470 FileStatusList: Indicate active file filter and regex error
  GitUI/UserControls/FileStatusList.cs
  UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs
Labels: status: ready

#6496 Use binary git-tree-ish blobdata to display binary files
  GitUI/Editor/FileViewer.cs
Labels: status: ready

#6445 Separate submodule structure and status
  GitCommands/Submodules/SubmoduleInfo.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Submodules.cs
Labels: status: ready

#6501 Update english translations
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/English.xlf
Labels: status: ready

#6256 Manually handle Ctrl+Backspace on TextBox and ComboBox controls
  GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Labels: status: cla signed, status: needs review

#6499 Generate avatars with author initials as fallback of gravatar
  GitCommands/Settings/DefaultImageType.cs
  GitUI/Avatars/AvatarDownloader.cs
  GitUI/Avatars/AvatarMemoryCache.cs
  GitUI/Avatars/AvatarPersistentCache.cs
  GitUI/Avatars/AvatarService.cs
  GitUI/Avatars/BackupAvatarProvider.cs
  GitUI/Avatars/IAvatarGenerator.cs
  GitUI/Avatars/IAvatarProvider.cs
  GitUI/Avatars/InitialsAvatarGenerator.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/GitUI.csproj
  GitUI/UserControls/AvatarControl.cs
  GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
  Plugins/Gource/GourceStart.cs
  UnitTests/GitUITests/Avatars/AvatarCacheTestBase.cs
  UnitTests/GitUITests/Avatars/AvatarMemoryCacheTests.cs
  UnitTests/GitUITests/Avatars/AvatarPersistentCacheTests.cs
  UnitTests/GitUITests/Avatars/AvatarTestBase.cs
  UnitTests/GitUITests/Avatars/BackupAvatarProviderTests.cs
  UnitTests/GitUITests/Avatars/InitialsAvatarGeneratorTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: needs review

#6505 Bugfix/settings appearance
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: status: ready, type: regression

#6502 correctly detect/handle script options
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/Script/ScriptRunner.cs
Labels: status: needs review

#6508 Checkout branch: Fix inopportune line return in message box message
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/Translation/English.xlf
Labels: status: needs review

#6511 Include source branch in link to BitBucket create pull request
  Plugins/Bitbucket/BitbucketPlugin.cs
  Plugins/Bitbucket/BitbucketPullRequestForm.cs
Labels: status: ready
