Repository gitextensions/gitextensions, pull requests merged in 2019-11, with the labels that each got.

#7377 fix incorect use of TestAccessor struct
  GitCommands/CommitMessageManager.cs
  GitCommands/Git/AheadBehindDataProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
  GitUI/CommandsDialogs/ToolStripPushButton.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/NBugReports/BugReportForm.cs
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/UserControls/PathFormatter.cs
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/CommonTestUtils/NoAssertContext.cs
  UnitTests/GitCommandsTests/CommitMessageManagerTests.cs
  UnitTests/GitCommandsTests/RevisionReaderTests.cs
Labels: status: auto merge

#7186 Limit removable for "Contained in branches/tags"
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/RefsFormatter.cs
  GitUI/GitUI.csproj
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
  ResourceManager/LinkFactory.cs
  ResourceManager/Strings.cs
  UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
  UnitTests/GitUITests/CommitInfo/RefsFormatterTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: area: user experience, status: auto merge, status: ready

#7343 Show syntax highlighting also when displaying a diff
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUI.csproj
  GitUI/GitUIExtensions.cs
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/Resources/Icons/SyntaxHighlighting.png
  GitUI/Translation/English.xlf
  UnitTests/GitUITests/Editor/FileViewerTextTests.cs
Labels: status: auto merge

#7398 fix: Crash on Missing Settings Directory
  GitCommands/Settings/FileSettingsCache.cs
  UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs
Labels: status: auto merge

#7399 CommitMessage: Only save if directory exists
  GitCommands/CommitMessageManager.cs
  UnitTests/GitCommandsTests/CommitMessageManagerTests.cs
Labels: status: auto merge

#7408 fix: FormResolveConflicts incorrect row selection
  GitUI/CommandsDialogs/FormResolveConflicts.cs
Labels: :beetle: type: bug, area: user experience

#7411 FormReflog : fix crash when switching from reference
  GitUI/CommandsDialogs/FormReflog.cs
Labels: status: auto merge

#7401 Extends Squash feature to all supported types
  GitUI/Translation/English.Plugins.xlf
  Plugins/GitFlow/GitFlowForm.Designer.cs
  Plugins/GitFlow/GitFlowForm.cs
Labels: :pen: status: cla signed, area: plugins

#7423 fix: SetRevisionFunc produce empty dropdown
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
  UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
Labels: status: auto merge

#7421 Update packages
  GitCommands/GitCommands.csproj
  GitExtensions/app.config
  GitUI/GitUI.csproj
  GitUI/app.config
  Plugins/BackgroundFetch/BackgroundFetch.csproj
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsIntegration.csproj
  Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsIntegration.csproj
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityIntegration.csproj
  Plugins/BuildServerIntegration/TfsIntegration/TfsIntegration.csproj
  Plugins/Gerrit/app.config
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Setup/MakePortableArchive.cmd
  Setup/Product.wxs
Labels: status: auto merge

#7400 catch cannot write to settings
  GitCommands/Settings/FileSettingsCache.cs
  UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs
Labels: status: auto merge

#7427 Regression: #7408 exception if no files are conflicted
  GitUI/CommandsDialogs/FormResolveConflicts.cs
Labels: status: auto merge, type: regression

#7448 Apply timeouts to JoinTillEmptyAsync
  Directory.Build.targets
  GitExtUtils/GitUI/ThreadHelper.cs
  UnitTests/CommonTestUtils/AsyncTestHelper.cs
  UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitUITests/ThreadHelperTests.cs
Labels: area: tests

#7460 Removes extra dot from Save as revfiletree dialog
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  contributors.txt
Labels: :pen: status: cla signed
