Repository gitextensions/gitextensions, pull requests merged in 2019-03, with the labels that each got.

#6324 Minor cleanup
  GitCommands/Git/GitModule.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: ready

#6321 Preserve original byte order mark when editing files
  GitUI/CommandsDialogs/FormEditor.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/GitUITests/CommandsDialogs/FormEditorTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6327 Fix test dependent on file watcher delay
  UnitTests/GitUITests/Editor/FileViewerTextTests.cs
Labels: status: ready

#6325 Throw OperationCanceledException on cts.Next() when cts is disposed.
  GitExtUtils/GitUI/CancellationTokenSequence.cs
  UnitTests/GitUITests/CancellationTokenSequenceTests.cs
Labels: status: ready

#6333 sign contributors.txt
  contributors.txt
Labels: status: needs review

#6209 #left-panel add "checkout" group context menu items for local branches
  GitUI/BranchTreePanel/ContextMenu/IMenuItemFactory.cs
  GitUI/BranchTreePanel/ContextMenu/IMenuItemsGenerator.cs
  GitUI/BranchTreePanel/ContextMenu/LocalBranchMenuItems.cs
  GitUI/BranchTreePanel/ContextMenu/MenuItemKey.cs
  GitUI/BranchTreePanel/ContextMenu/MenuItemsGenerator.cs
  GitUI/BranchTreePanel/ContextMenu/MenuItemsStrings.cs
  GitUI/BranchTreePanel/ContextMenu/RemoteBranchMenuItems.cs
  GitUI/BranchTreePanel/ContextMenu/TagMenuItems.cs
  GitUI/BranchTreePanel/Interfaces/ICanDelete.cs
  GitUI/BranchTreePanel/Interfaces/ICanRename.cs
  GitUI/BranchTreePanel/Interfaces/IGitRefActions.cs
  GitUI/BranchTreePanel/Interfaces/INode.cs
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  UnitTests/GitUITests/BranchTreePanel/GitRefMenuItemsTest.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: cla signed, status: needs review

#6316 Disable the display of notes Dialog after Ctrl+Shift+N for artificial…
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: cla signed

#6335 Sorted refs needs to be refreshed after the repository has changed.
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6342 Sign Developer Certificate of Origin
  contributors.txt
Labels: status: needs review

#5617 Feature: add a Submodules tree to the left panel
  GitCommands/Git/GitModule.cs
  GitCommands/GitCommands.csproj
  GitCommands/Settings/AppSettings.cs
  GitCommands/Submodules/SubmoduleInfoResult.cs
  GitCommands/Submodules/SubmoduleStatusEventArgs.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/BranchTreePanel/RepoObjectsTree.resx
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  GitUI/GitUIExtensions.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/TreeViewExtensions.cs
  Plugins/GitUIPluginInterfaces/IBrowseRepo.cs
  ResourceManager/Strings.cs
  UnitTests/CommonTestUtils/AsyncTestHelper.cs
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Remotes.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Submodules.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/TreeViewExtensionsTests.cs
Labels: status: ready, waffle:needs review

#6318 Quote submodule path to avoid black screen issue
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
  contributors.txt
Labels: status: cla signed, status: ready

#6337 FileStatusList: Show the hint "Filter files..." only when applicable
  GitUI/UserControls/FileStatusList.cs
  UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: needs review

#6351 Remove count on Branches and Tags
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: status: ready

#6352 Fix not being able to save changes to an existing remote
  GitUI/CommandsDialogs/FormRemotes.cs
Labels: status: ready

#6349 Left pane reorder trees
  GitCommands/Settings/AppSettings.cs
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.ReorderNodes.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6362 Support Git pre 2.11 for status
  GitCommands/Git/GitCommandHelpers.cs
Labels: status: ready

#6137 Diff List sorting options
  GitCommands/DiffListSortService.cs
  GitCommands/Git/GitItemStatusFileExtensionComparer.cs
  GitCommands/GitCommands.csproj
  GitCommands/IDiffListSortService.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/GitUI.csproj
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/SortBy.png
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/SortDiffListContextMenuItem.cs
  UnitTests/GitCommandsTests/DiffListSortServiceTests.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/GitItemStatusFileExtensionComparerTests.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/SortDiffListContextMenuItemTests.cs
Labels: status: cla signed, status: needs review

#6315 Fix reset function for copied files
  GitUI/CommandsDialogs/RevisionDiffControl.cs
Labels: status: cla signed, status: needs review

#6383 FormAbout: fix "Git Extensions is open source. Get involved!" text wa…
  GitUI/CommandsDialogs/FormAbout.Designer.cs
Labels: status: cla signed, status: needs review

#6301 Automatically load PuTTY SSH key files when needed in left panel
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
  GitUI/GitUICommands.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/PullFetchPrune.png
  GitUI/Resources/Icons/PullFetchPruneAll.png
  GitUI/Translation/English.xlf
Labels: status: cla signed, status: needs review

#6359 GitModule Encoding lazy encoding
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Patches/PatchProcessor.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
  UnitTests/GitCommandsTests/Patches/PatchProcessorTest.cs
Labels: status: ready

#6384 [#6147] Sign developer certificate of origin
  contributors.txt
Labels: status: needs cla, status: needs review

#6390 Fix exception thrown GitModule.GetRemotes on an invalid git directory
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitUICommands.cs
Labels: status: ready

#6399 Fix blame control click hold move mouse to the right
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/IFileViewer.cs
  GitUI/UserControls/BlameControl.cs
Labels: status: ready

#6400 Improve blame contextual menu
  GitUI/GitUI.csproj
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/UserControls/BlameControl.Designer.cs
  GitUI/UserControls/BlameControl.cs
Labels: status: needs review

#6393 Some improvments on blame form
  GitCommands/Git/GitBlame.cs
  GitUI/UserControls/BlameControl.cs
  UnitTests/GitCommandsTests/Git/GitBlameCommitTests.cs
Labels: status: needs review, status: ready

#6398 #6170 Fix PathTooLongException for files whose path is shorter than 260 characters
  GitUI/Editor/FileViewer.cs
  contributors.txt
Labels: status: needs review

#6330 Add depth option to GitHub Fork/Clone form
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
Labels: status: cla signed, status: ready

#6392 Fix vertical ruler position not correctly read from settings
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
Labels: status: cla signed, status: needs review

#6380 Exception for combined diff in CommitInfo
  GitUI/UserControls/CommitDiff.cs
Labels: status: ready

#6397 6198 ignore whitespace changes
  GitCommands/GitCommands.csproj
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/IgnoreWhitespaceKind.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/WhitespaceIgnore.png
  GitUI/Resources/Icons/WhitespaceIgnoreAll.png
  GitUI/Resources/Icons/WhitespaceIgnoreEol.png
  GitUI/Translation/English.xlf
  UnitTests/GitUITests/Editor/FileViewerTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: cla signed

#6421 Sign Developer Certificate of Origin
  contributors.txt
Labels: status: needs review

#6406 refactor: Rename IGitRemoteManager to IConfigFileRemoteSettingsManager
  GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs
  GitCommands/GitCommands.csproj
  GitCommands/Remotes/ConfigFileRemote.cs
  GitCommands/Remotes/ConfigFileRemoteSaveResult.cs
  GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/UserControls/RemotesComboboxControl.cs
  UnitTests/GitCommandsTests/ExternalLinks/ExternalLinkRevisionParserTests.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/Remote/ConfigFileRemoteSettingsManagerTests.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Remotes.cs
Labels: status: ready

#6408 Fix issue #6296: Incorrect context menu items in commit diff tab
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs
Labels: status: cla signed

#6426 AppVeyor plugin: Prevent crash when trying to add the same project again
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
Labels: status: needs review
