Repository gitextensions/gitextensions, pull requests merged in 2019-10, with the labels that each got.

#7216 Support older Gerrit API
  Plugins/Gerrit/FormGerritBase.cs
  Plugins/Gerrit/FormGerritPublish.cs
Labels: :pen: status: cla signed

#7230 Dont confirm switch worktree option
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/Translation/English.xlf
Labels: :pen: status: cla signed

#7208 Add ability to specify commit message on the command line
  GitCommands/CommitMessageManager.cs
  GitUI/CommandsDialogs/FormCommandlineHelp.resx
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/GitUICommands.cs
  UnitTests/GitCommandsTests/CommitMessageManagerTests.cs
Labels: status: auto merge

#7214 Allow multiple push url for git-remote
  GitCommands/Git/GitModule.cs
  GitCommands/Remotes/ConfigFileRemote.cs
  GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  Plugins/GitUIPluginInterfaces/Remote.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: auto merge

#7218 Fix #6593: GitExtension Exception resetting 1500 files in Diff tab.
  GitCommands/ArgumentBuilderExtensions.cs
  GitCommands/Git/ExecutableExtensions.cs
  GitCommands/Git/GitModule.cs
  GitUI/UserControls/FileStatusList.cs
  UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
  UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs
  contributors.txt
Labels: status: auto merge

#7280 Implement quotePath-like codepoint escaping
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: :scroll: status: needs cla, status: auto merge

#7288 Implement quotePath-like codepoint escaping
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
  contributors.txt
Labels: :pen: status: cla signed

#7252 Remove `ArgumentBuilder.Length` property
  GitCommands/ArgumentBuilderExtensions.cs
  GitCommands/CommitDataManager.cs
  GitCommands/FileHelper.cs
  GitCommands/Git/AheadBehindDataProvider.cs
  GitCommands/Git/ExecutableExtensions.cs
  GitCommands/Git/GitCheckoutBranchCmd.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitDeleteBranchCmd.cs
  GitCommands/Git/GitDeleteRemoteBranchesCmd.cs
  GitCommands/Git/GitGpgController.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitPushAction.cs
  GitCommands/Git/RevisionDiffProvider.cs
  GitCommands/Git/SystemEncodingReader.cs
  GitCommands/Git/Tag/GitCreateTagCmd.cs
  GitCommands/RevisionReader.cs
  GitExtUtils/ArgumentBuilder.cs
  GitExtUtils/ArgumentString.cs
  GitExtUtils/GitArgumentBuilder.cs
  GitExtUtils/GitCommandConfiguration.cs
  GitExtUtils/GitConfigItem.cs
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/Properties/AssemblyInfo.cs
  GitUI/CommandsDialogs/FormCherryPick.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormMergeSubmodule.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/FormVerify.LostObject.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
  GitUI/GitUICommands.cs
  GitUI/UserControls/ConsoleEmulatorOutputControl.cs
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
  Plugins/CreateLocalBranches/CreateLocalBranchesForm.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  Plugins/FindLargeFiles/FindLargeFilesForm.cs
  Plugins/Gerrit/FormGerritPublish.cs
  Plugins/Gerrit/GerritUtil.cs
  Plugins/GitFlow/GitFlowForm.cs
  Plugins/Gource/GourceStart.cs
  Plugins/ProxySwitcher/ProxySwitcherForm.cs
  UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
  UnitTests/GitCommandsTests/Config/ConfigFileTest.cs
  UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs
  UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
  UnitTests/GitExtUtils/ArgumentBuilderTests.cs
  UnitTests/GitExtUtils/GitArgumentBuilderTests.cs
Labels: status: auto merge

#7296 fix: missing method ResourceManager.GitPluginBase..ctor
  ResourceManager/GitPluginBase.cs
  TranslationApp/TranslationHelpers.cs
Labels: status: auto merge

#7284 Fix #7257 ConEmu is missing
  GitUI/CommandsDialogs/FormBrowse.cs
  contributors.txt
Labels: :pen: status: cla signed

#7276 Allow remote repositories with local disk path to be saved in recents
  GitCommands/UserRepositoryHistory/RemoteRepositoryManager.cs
Labels: :pen: status: cla signed

#7268 Add Squash feature on GitFlow Plugin Form
  GitUI/Translation/English.Plugins.xlf
  Plugins/GitFlow/GitFlowForm.Designer.cs
  Plugins/GitFlow/GitFlowForm.cs
  contributors.txt
Labels: :pen: status: cla signed

#7305 Allow branch creation in folder context menu (#7013)
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/CommandsDialogs/FormCreateBranch.cs
  GitUI/GitUICommands.cs
  GitUI/Translation/English.xlf
Labels: :pen: status: cla signed

#7330 Consistent display of binary files
  GitUI/Editor/FileViewer.cs
Labels: status: auto merge

#7291 Highlight
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
  GitUI/Editor/Diff/DiffHighlightService.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/IFileViewer.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  UnitTests/GitUITests/Editor/FileViewerTextTests.cs
  contributors.txt
Labels: type: feature request

#7349 Incorrect tab order on multiple settings pages #7301
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/Settings/SettingsUserControl.Designer.cs
  Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.Designer.cs
Labels: status: auto merge

#7365 Fix 7364: "Fetch and Prune All" confirmation modal has weird focus behavior
  GitUI/CommandsDialogs/FormPull.cs
Labels: status: auto merge

#7302 Document that PowerShell scripts are run detached
  GitUI/Script/ScriptRunner.cs
  Plugins/GitUIPluginInterfaces/IGitPlugin.cs
Labels: :eyeglasses: status: needs review, status: auto merge, status: ready

#7300 Incorrect placement of update submodules on checkout setting #7290
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/GitUICommands.cs
  GitUI/MessageBoxes.cs
  GitUI/Translation/English.xlf
Labels: :pen: status: cla signed, status: auto merge

#7369 Commit messages menu: Fix (sometimes) broken display
  GitUI/CommandsDialogs/FormCommit.cs
  UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Labels: area: user experience

#7373 Skip duplicate ref entries when building the Sorted Refs Dictionary
  GitUI/CommitInfo/CommitInfo.cs
  UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
  contributors.txt
Labels: :scroll: status: needs cla
