Repository gitextensions/gitextensions, pull requests merged in 2019-06, with the labels that each got.

#6682 Feature: Download / Install MSI without redirect to Browser
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  Setup/Product.wxs
Labels: status: cla signed

#6515 Fix GitHub PR protocol
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  Plugins/GitHub3/GitHubRepo.cs
Labels: status: needs review

#6651 Dark theme fixes
  GitExtUtils/GitUI/ControlDpiExtensions.cs
  GitUI/ColorHelper.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/FormAbout.cs
  GitUI/CommandsDialogs/FormAddToGitIgnore.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormDeleteBranch.Designer.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.Designer.cs
  GitUI/CommandsDialogs/FormDeleteTag.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormMergeSubmodule.Designer.cs
  GitUI/CommandsDialogs/FormRenameBranch.Designer.cs
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/GitUI.csproj
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Properties/Resources.Designer.cs
  GitUI/Properties/Resources.resx
  GitUI/Resources/Icons/Delete_inv.png
  GitUI/Resources/Icons/Develop_inv.png
  GitUI/Resources/Icons/FileStatusRenamed_inv.png
  GitUI/Resources/Icons/GitHub32_inv.png
  GitUI/Resources/Icons/Link_inv.png
  GitUI/Resources/Icons/PullRequest_inv.png
  GitUI/Resources/Icons/RecoverLostObjects_inv.png
  GitUI/Resources/Icons/ShowWhitespace_inv.png
  GitUI/Resources/Icons/Translate_inv.png
  GitUI/Resources/Icons/WhitespaceIgnoreAll_inv.png
  GitUI/Resources/Icons/WhitespaceIgnoreEol_inv.png
  GitUI/Resources/Icons/WhitespaceIgnore_inv.png
  GitUI/Resources/Icons/branch_inv.png
  GitUI/Resources/Icons/github_inv.png
  GitUI/UserControls/FileStatusList.Designer.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs
Labels: status: cla signed, status: ready

#6417 Generate avatars with author initials
  GitCommands/GitCommands.csproj
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/AvatarProvider.cs
  GitCommands/Settings/DefaultImageType.cs
  GitCommands/Settings/GravatarFallbackAvatarType.cs
  GitCommands/Utils/EnumHelper.cs
  GitUI/Avatars/AvatarDownloader.cs
  GitUI/Avatars/AvatarService.cs
  GitUI/Avatars/InitialsAvatarGenerator.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/AvatarControl.Designer.cs
  GitUI/UserControls/AvatarControl.cs
Labels: type: discussion

#6766 Fixed Gerrit plugin using deprecated features
  GitUI/Translation/English.Plugins.xlf
  Plugins/Gerrit/FormGerritPublish.Designer.cs
  Plugins/Gerrit/FormGerritPublish.cs
  contributors.txt
Labels: status: cla signed

#6801 Refactor "Check for updates" dialog
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.resx
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/English.xlf
Labels: status: cla signed

#6328 GitHub: easily add upstream remote
  GitCommands/Git/GitModule.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/GitUICommands.cs
  GitUI/Plugin/PluginRegistry.cs
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/English.xlf
  Plugins/GitHub3/GitHub3Plugin.cs
  Plugins/GitHub3/GitHubHostedRemote.cs
  Plugins/GitHub3/GitHubRepo.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  Plugins/GitUIPluginInterfaces/Remote.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRemote.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/IRepositoryHostPlugin.cs
Labels: status: cla signed

#6847 Restore title of AppearanceSettingsPage
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/Translation/English.xlf
Labels: type: regression

#6860 FormCreateBranch: Improve UX of CheckBox "Checkout after create"
  GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
  GitUI/Translation/English.xlf
Labels: area: user experience

#6871 FormCommit: Fix overlapping labels
  GitUI/UserControls/FileStatusList.Designer.cs
  GitUI/UserControls/FileStatusList.cs
Labels: status: ready
