Repository gitextensions/gitextensions, pull requests merged in 2019-09, with the labels that each got.

#7092 Fix scrolling for committers label in statistics plugin
  Plugins/Statistics/GitStatistics/FormGitStatistics.Designer.cs
  contributors.txt
Labels: status: cla signed

#6664 Reintegration of PluginManager.
  Build/Download-PluginManager.ps1
  Build/Prepare-Artifacts.ps1
  Setup/MakePortableArchive.cmd
  Setup/PluginManager.wxs
  Setup/Prepare-Release.ps1
  Setup/Product.wxs
  Setup/Setup.wixproj
Labels: area: installer, area: plugins

#7047 Fix 3934 add force push with lease to the push dialog
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/Translation/English.xlf
Labels: status: cla signed

#7040 Jira commit hint plugin: fix some string not translated
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/English.xlf
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Labels: area: plugins, area: user experience

#7084 Let the copy menu entry appear expandable at startup
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Labels: status: cla signed

#7009 Remove KDiff3 hardcoding
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#7158 fix incorrect user-agent
  Plugins/GitHub3/GitHubCredentialsPrompt.cs
Labels: status: auto merge

#6491 Execute scripts also if RevisionGrid is not focused
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/GitModuleControl.cs
  GitUI/GitModuleForm.cs
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/Script/ScriptRunner.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
  UnitTests/GitUITests/Script/ScriptRunnerTests.cs
Labels: status: auto merge

#7128 Unblock special commit message
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#7198 Gerrit Plugin fixes/improvements
  GitUI/Translation/English.Plugins.xlf
  Plugins/Gerrit/FormGerritPublish.Designer.cs
  Plugins/Gerrit/FormGerritPublish.cs
  contributors.txt
Labels: :pen: status: cla signed
