Repository gitextensions/gitextensions, pull requests merged in 2019-05, with the labels that each got.

#6513 Do not parse invalid rev-parse responses
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6526 Format patch: fix patch creation when selection order is invalid (master)
  GitUI/CommandsDialogs/FormFormatPatch.cs
Labels: status: ready

#6525 Format patch: fix patch creation when selection order is invalid
  GitUI/CommandsDialogs/FormFormatPatch.cs
Labels: status: needs review

#6519 Remove duplicated implementation and call of function LoadSortedRefsAsync
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6430 Add settings to configure blame display
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/UserControls/BlameControl.Designer.cs
  GitUI/UserControls/BlameControl.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/BlameControlTests.cs
Labels: status: needs review

#6537 Avoid loading data of incoherent revisions (for 3.1)
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6536 Avoid loading data of incoherent revisions
  GitUI/CommitInfo/CommitInfo.cs
Labels: status: ready

#6529 Update README.md
  README.md
Labels: status: ready

#6545 fix: Mark portable version as such
  appveyor.yml
Labels: status: ready

#6544 Improved BlameControlTests
  GitUI/UserControls/BlameControl.cs
  UnitTests/GitUITests/UserControls/BlameControlTests.cs
Labels: status: ready

#6331 Changed GPG tab setting to show by default
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
  GitUI/Translation/English.xlf
Labels: status: cla signed, status: needs review

#6534 RevisionGrid: Add branch icons in contextual menu
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#6531 Fix rebase and apply patches displayed patches status
  GitCommands/Git/GitModule.cs
  GitCommands/Patches/PatchFile.cs
  GitUI/CommandsDialogs/FormApplyPatch.cs
  GitUI/CommandsDialogs/FormRebase.Designer.cs
  GitUI/CommandsDialogs/FormRebase.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/PatchGrid.cs
Labels: status: ready

#6560 fix: Invalid URI when open invalid path
  GitCommands/PathUtil.cs
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
  GitUI/Translation/English.xlf
  UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
  UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs
  UnitTests/GitUITests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs
  UnitTests/GitUITests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs
  UnitTests/GitUITests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
  UnitTests/GitUITests/CommandsDialogs/FormBrowseTests.cs
  UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitUITests/CommandsDialogs/FormInitTests.cs
  UnitTests/GitUITests/CommandsDialogs/FormOpenDirectoryTests.cs
  UnitTests/GitUITests/CommandsDialogs/FormPullTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6580 fix: Throws on `git remote` call outside git repo
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6588 Use `Ben.Demystifier` to display or report better stacktraces
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/ThreadHelper.cs
  Setup/MakePortableArchive.cmd
  Setup/Product.wxs
Labels: status: ready

#6586 fix: Throws on `git remote` call outside git repo
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: ready

#6573 Bugfix script option {sRemotePathFromUrl}
  GitUI/Script/ScriptOptionsParser.cs
  UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
Labels: status: ready

#6551 Loading user plugins from app data folder.
  GitCommands/Settings/AppSettings.cs
  GitUI/Plugin/PluginRegistry.cs
  GitUI/WindowPositionList.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
  Plugins/GitUIPluginInterfaces/PluginsPathScanner.cs
  UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj
  UnitTests/Plugins/GitUIPluginInterfacesTests/ManagedExtensibilityTests.cs
  UnitTests/Plugins/GitUIPluginInterfacesTests/PathScanningData/NotFoundPlugin/SubDir/NotFoundPlugin.dll
  UnitTests/Plugins/GitUIPluginInterfacesTests/PathScanningData/PluginInOwnDir/PluginInOwnDir.dll
  UnitTests/Plugins/GitUIPluginInterfacesTests/PathScanningData/PluginInRootDir.dll
  UnitTests/Plugins/GitUIPluginInterfacesTests/PluginsPathScannerTests.cs
Labels: area: plugins, status: cla signed, status: ready

#6514 Refactor: Create an enum GitProtocol.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  Plugins/GitHub3/GitHubRepo.cs
  Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
  Plugins/GitUIPluginInterfaces/RepositoryHosts/GitProtocol.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/GitProtocolExtensions.cs
  Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs
  UnitTests/Plugins/GitUIPluginInterfacesTests/GitProtocolTests.cs
  UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj
Labels: status: ready

#6500 VS2019 msbuild
  .gitattributes
  Setup/Build.cmd
  Setup/BuildGitExtNative.cmd
  Setup/MakeInstallers.cmd
  Setup/hMSBuild.bat
Labels: status: ready
