Repository gitextensions/gitextensions, pull requests merged in 2019-01, with the labels that each got.

#6022 Diff window exception when adding a submodule without history
  GitCommands/CommitDataManager.cs
Labels: status: ready

#6023 Exception if no current checkout when selecting current revision
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#5983 use --no-optional-locks for submodule status and stash list
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: ready

#6013 Fix ROT selected node ensuring visible without collapsing other nodes…
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/Native.cs
Labels: status: ready

#5974 Replace ConcurrentBag in RevisionGraph
  GitExtUtils/GitExtUtils.csproj
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: status: ready

#6017 Fix broken custom stash message
  GitCommands/Git/GitCommandHelpers.cs
  UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
Labels: status: needs review

#6002 Submodule reset: Delete new files
  GitCommands/ArgumentBuilderExtensions.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
  GitUI/CommandsDialogs/FormCleanupRepository.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/GitUICommands.cs
  GitUI/HelperDialogs/FormResetCurrentBranch.cs
  Plugins/Gerrit/FormGerritDownload.cs
  UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
  UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: ready

#6027 Fix 6002 submodule reset delete new files
  GitCommands/ArgumentBuilderExtensions.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
  GitUI/CommandsDialogs/FormCleanupRepository.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/GitUICommands.cs
  GitUI/HelperDialogs/FormResetCurrentBranch.cs
  Plugins/Gerrit/FormGerritDownload.cs
  UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
  UnitTests/GitCommandsTests/GitModuleTest.cs
Labels: status: ready

#5955 Introduce separate issue templates for bugs and feature requests
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: status: ready

#6041 Hide depreciated lfs-clone option
  GitCommands/Git/GitVersion.cs
  GitUI/CommandsDialogs/FormClone.cs
Labels: status: ready

#5995 Fix recent repo dropdown favourites ordering
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6026 Git Notes not displayed in Commit info
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitRevision.cs
  GitCommands/RevisionReader.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#6058 revision link fixes
  GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
Labels: status: ready

#6020 Indicate unknown commit status
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/BrowseDialog/GitWorkingDirectoryStatusEventArgs.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/RepoStateUnknown.png
  GitUI/Resources/Icons/RepoStateUntrackedOnly.png
  GitUI/Translation/English.xlf
  GitUI/UserControls/RepoStateVisualiser.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitUITests/UserControls/RepoStateVisualiserTests.cs
Labels: status: needs review

#6059 Fix copying RichTextBox text and restore context menu for CommitInfoHeader
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
Labels: status: needs review

#6049 #6029 fix broken multiline textboxes
  GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Labels: status: needs review

#6061 Make left panel remote fetch use the same function as FormBrowse
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
Labels: status: ready

#6087 Fix 6075 update gh issues link
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  Plugins/Gerrit/FormGitReview.cs
  Plugins/Gerrit/FormPluginInformation.cs
Labels: status: ready

#6085 Fix possible ArgumentException on startup
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: needs review

#6081 Fix "Delete all" context action on branch folder in left panel
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/CommandsDialogs/FormDeleteBranch.cs
Labels: status: ready

#6098 Feature/6094
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Labels: status: ready

#6089 Add context menu item "Copy link" to Commit Info
  GitUI/CommitInfo/CommitInfo.Designer.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
  UnitTests/GitUITests/Editor/RichTextBoxXhtmlSupportExtensionTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: needs review

#6073 Amaiorano/left panel remotes improvements
  GitCommands/Remotes/GitRemoteManager.cs
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/GitUI.csproj
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/RemoteEnableAndFetch.png
  GitUI/Translation/English.xlf
  GitUI/UserControls/NativeTreeViewDoubleClickDecorator.cs
  GitUI/UserControls/TreeViewExtensions.cs
Labels: status: ready

#6091 Allow toggle 'simplify-merges'
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormFileHistory.resx
Labels: status: needs review

#6056 Avoid adding newline at the end of formatted output
  GitCommands/Git/GitModule.cs
Labels: status: ready

#6042 Update Git recommended version to 2.20.1
  GitCommands/Git/GitVersion.cs
Labels: status: ready

#6108 Add tests for TreeViewExtensions.GetExpandedNodesState and RestoreExp…
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/GitUITests/UserControls/TreeViewExtensionsTests.cs
Labels: status: ready

#6107 Fix side panel sometimes ending up with duplicate sets of remotes whe…
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
Labels: status: ready

#6100 Tests for GitRemoteManager.GetDisabledRemotes, GetDisabledRemoteNames…
  GitCommands/Remotes/GitRemoteManager.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6130 FormPush: populate available remotes on changes
  GitUI/CommandsDialogs/FormPush.cs
Labels: status: needs review

#6105 AutoCompleteWord git-status must not lock git
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Labels: status: ready

#6123 #5981 superproject-refs for 3.0
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: ready

#6037 Solved column size problem in FileStatusList
  GitUI/UserControls/ExListView.cs
  GitUI/UserControls/FileStatusList.Designer.cs
  GitUI/UserControls/FileStatusList.cs
Labels: status: more info requested, status: needs review

#6145 Update README.md
  README.md
Labels: status: needs review

#6125 Use high DPI mouse cursors
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/HighDpiMouseCursors.cs
  GitExtensions/Program.cs
Labels: status: ready

#6124 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  contributors.txt
Labels: status: ready

#6111 Fix AE: Can not add a section that already exists: -remote
  GitCommands/Remotes/GitRemoteManager.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs
  UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs
Labels: status: ready

#6166 Signed off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: ready

#6167 Signed off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: needs review

#6101 Update View menu items when toggled
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  contributors.txt
Labels: status: cla signed, status: needs cla, status: ready

#6156 fix Win32ApiTests against x86 platform
  UnitTests/GitExtUtils/Win32ApiTests.cs
  contributors.txt
Labels: status: more info requested, status: needs cla, status: needs review

#6134 Fix reset selected lines
  GitUI/CommandsDialogs/FormCommit.cs
  ResourceManager/GitExtensionsFormBase.cs
  ResourceManager/NativeMethods.cs
  ResourceManager/ResourceManager.csproj
Labels: status: cla signed, status: ready

#6153 Fix #6144, it should treat none as default.
  GitUI/CommandsDialogs/FormPull.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormPullTests.cs
  contributors.txt
Labels: status: needs cla, status: ready

#6112 Restore green Commit icon in Task Bar Jump List
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: area: user experience, status: ready, type: regression

#6009 Use native methods instead of recursion for resolving correct path casing
  GitCommands/PathUtil.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormFileHistoryController.cs
  GitUI/GitUI.csproj
  UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
  UnitTests/GitUITests/CommandsDialogs/FormFileHistoryControllerTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: ready

#6159 Fix loading of some plugins that failed
  Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
Labels: status: cla signed, status: needs review

#6065 Introduce option to disable build result tab #6063
  GitCommands/Settings/RepoDistSettings.cs
  GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs
  contributors.txt
Labels: status: needs cla, status: needs review

#6152 Fix #6144, it should treat none as default.
  GitUI/CommandsDialogs/FormPull.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormPullTests.cs
  UnitTests/GitUITests/GitUITests.csproj
Labels: status: cla signed, status: needs review

#6157 fix FileStatusList layout after replacing Dock.Fill by Anchor
  GitUI/UserControls/FileStatusList.Designer.cs
  GitUI/UserControls/FileStatusList.cs
Labels: status: cla signed, status: ready

#6177 Fix a bug introduced in #5994 where if active branch is ahead/behind,…
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: status: ready

#6176 Refactor and optimize AheadBehind code in left panel
  GitCommands/Git/AheadBehindDataProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/CommandsDialogs/ToolStripPushButton.cs
  UnitTests/GitUITests/UserControls/ToolStripPushButtonTests.cs
Labels: status: ready

#6184 Signed off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: needs review

#6188 Signed off the project's Contributors Certification of Origin and Rights
  contributors.txt
Labels: status: needs review

#6169 Fix sorting of commit templates.
  GitCommands/CommitTemplateManager.cs
  UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs
Labels: status: cla signed, status: needs review

#5669 Pub/sub for the left panel
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: in progress, status: ready

#6122 Copy selected diff text to commit message
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Labels: status: cla signed, status: needs review
