Repository gitextensions/gitextensions, pull requests merged in 2020-10, with the labels that each got.

#8414 Filter out hidden branches
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/ICheckRefs.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
Labels: area: left-panel

#8496 FileViewer: ViewMode to track what is currently displayed
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/Editor/FileViewer.cs
Labels: status: auto merge

#8511 Don't refresh revision grid invoking toolstrip actions
  GitUI/FilterBranchHelper.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: hacktoberfest-accepted

#8515 Push multiple: Set default push to false
  GitUI/CommandsDialogs/FormPush.Designer.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/Translation/English.xlf
Labels: hacktoberfest-accepted, status: auto merge

#8501 Apply action to all selected files in solve merge conflict
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/ResolveConflictsDialog/FormModifiedDeletedCreated.Designer.cs
  GitUI/CommandsDialogs/ResolveConflictsDialog/FormModifiedDeletedCreated.cs
  GitUI/CommandsDialogs/ResolveConflictsDialog/FormModifiedDeletedCreated.resx
  GitUI/Translation/English.xlf
  contributors.txt
Labels: :pen: status: cla signed, hacktoberfest-accepted

#8528 Use SelectedNode property to track target for context menu
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
Labels: hacktoberfest-accepted

#8523 [#5499] Fix invisible row selection in the file status list control.
  GitExtUtils/GitUI/Theming/ColorHelper.cs
  GitUI/UserControls/FileStatusList.cs
  UnitTests/GitExtUtils.Tests/ColorTransformationTests.cs
  contributors.txt
Labels: :pen: status: cla signed, hacktoberfest-accepted, status: auto merge

#8527 updated removeFiles to use GetBatchOutput and added unit tests
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: :pen: status: cla signed, hacktoberfest-accepted

#8525 Submodules window now keeps the splitter position
  GitUI/CommandsDialogs/FormSubmodules.cs
  contributors.txt
Labels: :pen: status: cla signed, hacktoberfest-accepted

#6339 Add ability to Copy to Clipboard, similar to commit context menu from left panel
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Labels: :pen: status: cla signed, area: left-panel

#8502 Add a button to be able to open Application and User theme folders
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.resx
  GitUI/Translation/English.xlf
Labels: hacktoberfest-accepted

#8533 BackgroundFetch & push --force-with-lease : add a warning message
  Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
Labels: area: plugins, hacktoberfest-accepted

#8524 Ensure focus is on cancel button for Reset Form
  GitUI/CommandsDialogs/FormResetChanges.Designer.cs
Labels: :pen: status: cla signed, hacktoberfest-accepted, status: auto merge

#8471 support for range-diff
  GitCommands/Git/GitItemStatus.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitVersion.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/GitUIExtensions.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusDiffCalculator.cs
  GitUI/UserControls/FileStatusItem.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/FileStatusWithDescription.cs
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.fatal_error.approved.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_ignored_files.approved.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_modified_files.approved.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_staged_files.approved.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_untracked_files.approved.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_with_spaces.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_spaces_are_not_trimmed_in_file_names.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_the_staged_status_is_None_if_not_IndexWorkTree1.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_the_staged_status_is_None_if_not_IndexWorkTree2.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Ignore_unmerged_in_conflict_if_revision_is_work_tree.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Include_unmerged_in_conflict_if_revision_is_index.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Rename_with_spaces.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree1.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree2.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree3.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree4.approved.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.fatal_error.approved.json
  UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Labels: status: auto merge

#8541 Fixes #8327 push commit does clear commit message
  GitUI/CommandsDialogs/FormCommit.cs
Labels: hacktoberfest-accepted, status: auto merge

#8543 Add ability to show "Add submodule" Dialog on taskbar.
  GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.Designer.cs
Labels: hacktoberfest-accepted

#8532 Detect when Azure DevOps token is invalid/expired
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsIntegration.csproj
  Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
  Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs
  Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerAdapter.cs
  Plugins/GitUIPluginInterfaces/IGitUICommands.cs
  Solution.Versions.props
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/AppVeyorAdapterTests.cs
Labels: area: plugins, hacktoberfest-accepted

#8549 FormPush multiple: force-with-lease if rejected
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#8405 Add 'Run script' command to branches pane context menu
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
  GitUI/Script/IRunScript.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: area: left-panel, area: scripting

#8555 update button mnemonic for Reset button on Reset Form to "E"
  GitUI/CommandsDialogs/FormResetChanges.Designer.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#8510 Update layout
  GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
  GitUI/CommandsDialogs/FormClone.Designer.cs
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormInit.Designer.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/GitExtensionsDialog.Designer.cs
  GitUI/HelperDialogs/FormStatus.Designer.cs
  GitUI/HelperDialogs/FormStatus.cs
  GitUI/UserControls/ConsoleEmulatorOutputControl.cs
Labels: hacktoberfest-accepted, status: auto merge

#8537 Fixes #8146 "Keyboard navigation : Enter Key should open a recent repository"
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: hacktoberfest-accepted

#8559 Add dialog help that navigates to the docs
  GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
  GitUI/CommandsDialogs/FormClone.Designer.cs
  GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
  GitUI/CommandsDialogs/FormInit.Designer.cs
  GitUI/GitExtensionsDialog.Designer.cs
  GitUI/GitExtensionsDialog.cs
Labels: hacktoberfest-accepted

#8504 Parallelized Repo Validity Checks during Startup
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Labels: hacktoberfest-accepted

#8556 Fixes #7557 - Dashboard: GitHub clone shortcut missing at initial load
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: hacktoberfest-accepted

#8550 gray additional commit lines in revision grid
  GitExtUtils/GitUI/Theming/ColorHelper.cs
  GitUI/UserControls/RevisionGrid/CellStyle.cs
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: hacktoberfest-accepted

#8563 Draw a separator line at the top of the footer panel, similar to what Task Dialog does
  GitUI/GitExtensionsDialog.cs
Labels: status: auto merge

#8506 FormEditor SaveCanges Changes
  GitExtUtils/FileUtility.cs
  GitUI/CommandsDialogs/FormEditor.cs
Labels: hacktoberfest-accepted, status: auto merge

#8529 Fix #8188: cannot force push tags
  GitUI/CommandsDialogs/FormPush.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPushTests.cs
Labels: hacktoberfest-accepted

#8562 Ahead/behind show up-to-date and gone
  GitCommands/Git/AheadBehindData.cs
  GitCommands/Git/AheadBehindDataProvider.cs
  UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
Labels: hacktoberfest-accepted

#8576 fix background / foreground contrast for gray text
  GitUI/Themes/dark.css
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: :mailbox_with_no_mail: needs: author feedback, area: theming

#8516 range-diff presentation
  GitUI/Editor/Diff/DiffHighlightService.cs
  GitUI/Editor/Diff/LinePrefixHelper.cs
  GitUI/Editor/Diff/RangeDiffHighlightService.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/GitUIExtensions.cs
Labels: hacktoberfest-accepted, status: auto merge
