Repository gitextensions/gitextensions, pull requests merged in 2020-05, with the labels that each got.

#8050 Unneeded rev-list for submodule status
  GitCommands/Git/GitCommandHelpers.cs
Labels: status: auto merge

#8059 Correct filemode for source files
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
Labels: status: auto merge

#8051 git-diff override diff.mnemonicprefix=true
  GitExtUtils/GitCommandConfiguration.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge

#8056 Select multiple revisions using Left Panel
  GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: :eyeglasses: status: needs review, area: user experience, status: auto merge

#8065 Align folder/copy for submodule
  GitUI/CommandsDialogs/FormCommit.Designer.cs
Labels: status: auto merge

#8078 Improve tooltip for diff selection
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge, type: translation changed

#8101 Limit number of diff revisions
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#8049 Fix 7097 crash invalid escape character in .gitmodule
  GitCommands/Config/ConfigFile.cs
  GitCommands/Config/GitConfigurationException.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormSubmodules.cs
  GitUI/MessageBoxes.cs
  GitUI/Translation/English.xlf
  Plugins/Statistics/GitStatistics/FormGitStatistics.cs
  ResourceManager/Strings.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Labels: type: translation changed

#8124 Restore splitter positions
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: area: user experience

#8067 Fix 8055 add sign-off to FormApplyPatch
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormApplyPatch.Designer.cs
  GitUI/CommandsDialogs/FormApplyPatch.cs
  GitUI/Translation/English.xlf
  UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
  contributors.txt
Labels: :pen: status: cla signed, type: translation changed

#8130 Support 0 options in ScriptOptionsParser.AskToSpecify
  GitUI/Script/ScriptOptionsParser.cs
Labels: area: scripting

#8132 Fix up repo preparation before verifying loc
  appveyor.yml
Labels: area: toolchain

#8035 Indicate merged branches in left panel
  GitCommands/Git/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/BranchDocument.png
  GitUI/Resources/Icons/BranchLocalMerged.png
  GitUI/Resources/Icons/BranchRemoteMerged.png
  UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
Labels: status: auto merge

#8141 SubmoduleStatusProvider: Set IsDirty from git-status
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: auto merge
