Repository gitextensions/gitextensions, pull requests merged in 2020-07, with the labels that each got.

#8275 RevFile: Diff any two files
  GitUI/CommandsDialogs/RememberFileContextMenuController.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#8287 Restore FileStatusList focus after GoToChild/Parent
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: area: user experience

#8269 Split VSIX into gitextensions/gitextensions.vsix
  GitExtensions.sln
  GitExtensionsVSIX/Commands/About.cs
  GitExtensionsVSIX/Commands/ApplyPatch.cs
  GitExtensionsVSIX/Commands/Blame.cs
  GitExtensionsVSIX/Commands/Browse.cs
  GitExtensionsVSIX/Commands/Cherry.cs
  GitExtensionsVSIX/Commands/Clone.cs
  GitExtensionsVSIX/Commands/CommandBase.cs
  GitExtensionsVSIX/Commands/Commit.cs
  GitExtensionsVSIX/Commands/CreateBranch.cs
  GitExtensionsVSIX/Commands/FileHistory.cs
  GitExtensionsVSIX/Commands/FindFile.cs
  GitExtensionsVSIX/Commands/FormatPatch.cs
  GitExtensionsVSIX/Commands/GitBash.cs
  GitExtensionsVSIX/Commands/GitIgnore.cs
  GitExtensionsVSIX/Commands/Init.cs
  GitExtensionsVSIX/Commands/ItemCommandBase.cs
  GitExtensionsVSIX/Commands/Merge.cs
  GitExtensionsVSIX/Commands/OpenWithDifftool.cs
  GitExtensionsVSIX/Commands/Pull.cs
  GitExtensionsVSIX/Commands/Push.cs
  GitExtensionsVSIX/Commands/Rebase.cs
  GitExtensionsVSIX/Commands/Remotes.cs
  GitExtensionsVSIX/Commands/Revert.cs
  GitExtensionsVSIX/Commands/Settings.cs
  GitExtensionsVSIX/Commands/SolveMergeConflicts.cs
  GitExtensionsVSIX/Commands/Stash.cs
  GitExtensionsVSIX/Commands/SwitchBranch.cs
  GitExtensionsVSIX/Commands/ToolbarCommand.cs
  GitExtensionsVSIX/Commands/ViewChanges.cs
  GitExtensionsVSIX/Commands/VsixCommandBase.cs
  GitExtensionsVSIX/Directory.Build.props
  GitExtensionsVSIX/Directory.Build.targets
  GitExtensionsVSIX/Git/GitCommands.cs
  GitExtensionsVSIX/GitExtCommandTable.cs
  GitExtensionsVSIX/GitExtCommandTable.vsct
  GitExtensionsVSIX/GitExtCommands.cs
  GitExtensionsVSIX/GitExtensionsPackage.cs
  GitExtensionsVSIX/GitExtensionsVSIX.csproj
  GitExtensionsVSIX/PluginHelpers.cs
  GitExtensionsVSIX/Properties/AssemblyInfo.cs
  GitExtensionsVSIX/Resources/Commands.png
  GitExtensionsVSIX/Resources/Commands.xcf
  GitExtensionsVSIX/source.extension.cs
  GitExtensionsVSIX/source.extension.ico
  GitExtensionsVSIX/source.extension.resx
  GitExtensionsVSIX/source.extension.vsixmanifest
  scripts/Mark-RepoClean.ps1
  scripts/set_version_to.py
Labels: area: vsix

#8296 Disable Finish button while loading branches in GitFlow form.
  Plugins/GitFlow/GitFlowForm.cs
Labels: :pen: status: cla signed

#8213 FormBrowse: Add all supported shells to the toolbar
  GitCommands/Git/GitModule.cs
  GitCommands/PathUtil.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommandlineHelp.resx
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
  GitUI/GitUI.csproj
  GitUI/GitUICommands.cs
  GitUI/MessageBoxes.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/cmd.png
  GitUI/Resources/Icons/powershell.png
  GitUI/Resources/Icons/pwsh.png
  GitUI/Script/ScriptRunner.cs
  GitUI/ShellHelper.cs
  GitUI/Shells/BashShell.cs
  GitUI/Shells/CmdShell.cs
  GitUI/Shells/ConEmuControlExtensions.cs
  GitUI/Shells/IShellDescriptor.cs
  GitUI/Shells/PowerShellShell.cs
  GitUI/Shells/PwshShell.cs
  GitUI/Shells/ShellDescriptor.cs
  GitUI/Shells/ShellProvider.cs
  GitUI/Translation/English.xlf
  IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
Labels: status: auto merge

#8298 Customise GitHub issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: status: auto merge

#8292 Dialogs layout alignment
  GitUI/CommandsDialogs/FormClone.Designer.cs
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormInit.Designer.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/GitExtensionsDialog.Designer.cs
  GitUI/GitExtensionsDialog.cs
  GitUI/GitExtensionsDialog.resx
  GitUI/GitModuleForm.cs
  GitUI/HelperDialogs/FormProcess.cs
  GitUI/HelperDialogs/FormRemoteProcess.cs
  GitUI/HelperDialogs/FormStatus.Designer.cs
  GitUI/HelperDialogs/FormStatus.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: area: user experience

#8212 Recover lost object: Add a file preview
  GitUI/CommandsDialogs/FormVerify.Designer.cs
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/FormVerify.resx
Labels: area: user experience

#8322 Fix Gource avatar feature
  Plugins/Gource/GourcePlugin.cs
  Plugins/Gource/GourceStart.cs
Labels: status: auto merge

#8311 Clean up of status reporting of failed operations
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormMergeSubmodule.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/HelperDialogs/FormProcess.cs
  GitUI/HelperDialogs/FormStatus.Designer.cs
  GitUI/HelperDialogs/FormStatus.cs
  GitUI/TaskbarProgress.cs
Labels: status: auto merge

#8239 RevDiff: Add hotkeys to stage/unstage/reset
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/MessageBoxes.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#8274 Avoid console printouts when submodule updates are throttled
  GitCommands/Submodules/SubmoduleStatusProvider.cs
Labels: status: auto merge

#8335 DiffTools: add 'tortoisediff' as a tool alias
  GitCommands/DiffMergeTools/TortoiseDiff.cs
  UnitTests/GitCommands.Tests/DiffMergeTools/RegisteredDiffMergeToolsTests.cs
Labels: status: auto merge
