Repository gitextensions/gitextensions, pull requests merged in 2020-01, with the labels that each got.

#7576 fix: Unable to update due to network configurations
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#7561 RevisionDiff: Show BASE diff
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7603 Merge branch dialog: Make form border style fixed and align checkboxes
  GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
Labels: :pen: status: cla signed

#7615 Convert and quote file names for BatchUnstageFiles
  GitCommands/ArgumentBuilderExtensions.cs
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: status: auto merge

#7569 Debug: add build branch to title
  GitCommands/AppTitleGenerator.cs
  GitExtensions/Program.cs
Labels: status: auto merge

#7558 RevisionDiff: No reset to CombinedDiff
  GitUI/CommandsDialogs/RevisionDiffControl.cs
Labels: status: auto merge

#7633 Check if path is valid before Path.Combine
  GitUI/CommandsDialogs/FormClone.cs
Labels: :pen: status: cla signed

#7646 Restore test Submodule_status_changes_for_top_module
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
Labels: area: tests, status: auto merge

#7647 Improve [Form]CommitInfoTests
  IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
Labels: area: tests, status: auto merge

#7651 ls-tree: Use -- to escape files starting with "-"
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommandsTests/Config/ConfigFileTest.cs
Labels: status: auto merge

#7654 Add TempAppSettingsAttribute for all tests
  IntegrationTests/UITests/Properties/AssemblyInfo.cs
  UnitTests/CommonTestUtils/Properties/AssemblyInfo.cs
  UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs
  UnitTests/GitCommandsTests/Properties/AssemblyInfo.cs
  UnitTests/GitExtUtils/GitExtUtilsTests.csproj
  UnitTests/GitExtUtils/Properties/AssemblyInfo.cs
  UnitTests/GitUITests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegrationTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegrationTests/AzureDevOpsIntegrationTests.csproj
  UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegrationTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/DeleteUnusedBranchesTests/DeleteUnusedBranchesTests.csproj
  UnitTests/Plugins/DeleteUnusedBranchesTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/GerritTests/GerritTests.csproj
  UnitTests/Plugins/GerritTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj
  UnitTests/Plugins/GitUIPluginInterfacesTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/ReleaseNotesGeneratorTests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj
  UnitTests/ResourceManagerTests/Properties/AssemblyInfo.cs
  UnitTests/ResourceManagerTests/ResourceManagerTests.csproj
Labels: area: tests, status: auto merge

#7626 Add A/B to RevisionDiff revision descriptions
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: auto merge

#7624 FileViewer context menu fixes
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormEditor.cs
  GitUI/CommandsDialogs/FormLog.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/CommitDiff.cs
  UnitTests/GitUITests/Editor/FileViewerTextTests.cs
Labels: status: auto merge

#7612 Improve speed of directory change in console tab
  GitUI/CommandsDialogs/FormBrowse.cs
  contributors.txt
Labels: :pen: status: cla signed

#7645 Cleanup tests
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
  IntegrationTests/UITests/CommandsDialogs/FileStatusListTests.cs
  IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs
  IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs
  IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
  IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.cs
  IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs
  IntegrationTests/UITests/CommandsDialogs/FormEditorTests.cs
  IntegrationTests/UITests/CommandsDialogs/FormInitTests.cs
  IntegrationTests/UITests/CommandsDialogs/FormPullTests.cs
  IntegrationTests/UITests/NBugReports/BugReportFormTests.cs
  IntegrationTests/UITests/Script/ScriptRunnerTests.cs
  IntegrationTests/UITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
  UnitTests/GitCommandsTests/ExternalLinks/ConfiguredLinkDefinitionsProviderTests.cs
  UnitTests/GitCommandsTests/ExternalLinks/ExternalLinksManagerIntegrationTests.cs
  UnitTests/GitUITests/Avatars/AvatarTestBase.cs
  UnitTests/GitUITests/BranchTreePanel/GitRefMenuItemsTest.cs
  UnitTests/GitUITests/CommandsDialogs/FormOpenDirectoryTests.cs
  UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs
  UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
  UnitTests/GitUITests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs
  UnitTests/GitUITests/Editor/FileViewerTests.cs
  UnitTests/GitUITests/Editor/FileViewerTextTests.cs
  UnitTests/GitUITests/GitExtensionsFormTests.cs
  UnitTests/GitUITests/UserControls/BlameControlTests.cs
Labels: area: tests

#7688 Disable flaky test GetSuperprojectCurrentCheckout
  UnitTests/GitCommandsTests/GitModuleTests.cs
Labels: area: tests

#7686 Do not deregister from Application.ThreadException between tests
  UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
Labels: area: tests

#7666 Add A/B to RevisionDiff revision descriptions #7626
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: auto merge

#7691 Update NUnit
  IntegrationTests/UITests/UITests.csproj
  UnitTests/CommonTestUtils/AssertEx.cs
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/GitCommandsTests/AsyncLoaderTests.cs
  UnitTests/GitCommandsTests/GitCommandsTests.csproj
  UnitTests/GitCommandsTests/GitModuleTests.cs
  UnitTests/GitExtUtils/GitExtUtilsTests.csproj
  UnitTests/GitUITests/ControlThreadingExtensionsTests.cs
  UnitTests/GitUITests/GitUITests.csproj
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegrationTests/AppVeyorIntegrationTests.csproj
  UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegrationTests/AzureDevOpsIntegrationTests.csproj
  UnitTests/Plugins/DeleteUnusedBranchesTests/DeleteUnusedBranchesTests.csproj
  UnitTests/Plugins/GerritTests/GerritTests.csproj
  UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj
  UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj
  UnitTests/ResourceManagerTests/ResourceManagerTests.csproj
Labels: area: tests

#7692 Join pending operations asynchronously
  IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
  IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs
  UnitTests/CommonTestUtils/AsyncTestHelper.cs
  UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
  UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
  UnitTests/GitUITests/ThreadHelperTests.cs
Labels: area: tests

#7690 FileViewer: Do not access the file system for git blobs
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormViewPatch.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  ResourceManager/LocalizationHelpers.cs
Labels: status: auto merge
