Repository gitextensions/gitextensions, pull requests merged in 2020-06, with the labels that each got.

#8175 FileStatusList context menu order
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Labels: status: auto merge

#8195 Do not use Cursor.Position in Mouse event handlers
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: :beetle: type: bug, area: user experience

#8204 Revert incomplete translations
  Setup/Product.wxs
Labels: area: toolchain

#8119 Submodule status: Throttle instead of drop frequent updates
  GitCommands/Submodules/SubmoduleInfoResult.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  UnitTests/CommonTestUtils/GitModuleTestHelper.cs
  UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
  UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Labels: status: auto merge

#8250 Fix "selection only" text search on Diff view (#7784)
  GitUI/Editor/FindAndReplaceForm.cs
  UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
Labels: :pen: status: cla signed

#8266 Fix ssh not found
  GitCommands/SshPathLocator.cs
  UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
Labels: :pen: status: cla signed

#8076 Run FormFileHistory in a separate GE instance
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/GitUICommands.cs
  IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
  Plugins/GitUIPluginInterfaces/IGitUICommands.cs
  UnitTests/GitUI.Tests/GitUICommands/NormalizeFileNameTests.cs
Labels: :eyeglasses: status: needs review, status: auto merge
