Repository gitextensions/gitextensions, pull requests merged in 2020-08, with the labels that each got.

#8038 Fix for #8030 URL in "Edit Remote Details"is case insensitive
  GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
  GitUI/CommandsDialogs/FormRemotes.Designer.cs
  GitUI/UserControls/CaseSensitiveComboBox.cs
Labels: :pen: status: cla signed

#8372 Optimise `FormSettings` load
  GitUI/CommandsDialogs/FormSettings.Designer.cs
  GitUI/CommandsDialogs/FormSettings.cs
Labels: area: performance, area: user experience

#8359 Dialogs layout alignment `FormCreateBranch`
  GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/CommandsDialogs/FormClone.Designer.cs
  GitUI/CommandsDialogs/FormInit.Designer.cs
  GitUI/GitExtensionsDialog.cs
  GitUI/HelperDialogs/FormStatus.Designer.cs
Labels: status: auto merge

#8384 Fixes #8348. Allow to create patch for the root commit.
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge

#8371 Added support for showing multi-line commit messages in the revision graph
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  contributors.txt
Labels: :pen: status: cla signed, area: performance, area: user experience

#8357 fix test: SaveImpl_should_throw_if_invalid_path
  GitCommands/Settings/FileSettingsCache.cs
  GitCommands/Settings/SaveSettingsException.cs
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/Translation/English.xlf
  UnitTests/GitCommands.Tests/Settings/FileSettingsCacheTests.cs
Labels: status: auto merge
