Repository gitextensions/gitextensions, pull requests merged in 2020-02, with the labels that each got.

#7711 gitex.cmd: handle quotes in commands
  Bin/gitex.cmd
Labels: status: auto merge

#7719 Refactor: Compare with ObjectId rather than Guid
  GitCommands/Git/GitModule.cs
  GitCommands/GitRevisionInfoProvider.cs
  GitUI/CommandsDialogs/FileStatusListContextMenuController.cs
  GitUI/CommandsDialogs/FormBrowseController.cs
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/UserControls/CommitDiff.cs
  GitUI/UserControls/FileStatusList.cs
  Plugins/GitUIPluginInterfaces/ObjectId.cs
Labels: status: auto merge

#7703 Addendum to Arcade build
  Build/Run-Tests.ps1
  Build/tools/DefaultVersions.props
  Build/tools/NUnit/NUnit.targets
  UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
  appveyor.yml
Labels: status: auto merge

#7736 Adapt colors for warning header with dark theme
  GitUI/UserControls/InteractiveGitActionControl.cs
Labels: status: auto merge

#7747 Update vs-threading analyzers and fix new diagnostics
  Directory.Build.targets
  GitExtUtils/GitUI/ThreadHelper.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Editor/FindAndReplaceForm.cs
  GitUI/UserControls/CommitDiff.cs
  GitUI/UserControls/MainThreadScheduler.cs
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/Settings/SettingsUserControl.cs
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
  UnitTests/GitUI.Tests/ControlThreadingExtensionsTests.cs
Labels: status: auto merge

#7741 fix: Plugins private binaries not resovled
  GitExtensions/GitExtensions.csproj
  Plugins/BuildServerIntegration/AppVeyorIntegration/app.config
Labels: area: plugins

#7750 Avoid attempting to update non-existent UI
  GitCommands/Utils/EnvUtils.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/TaskbarProgress.cs
  GitUI/WindowsJumpListManager.cs
Labels: status: auto merge

#7744 Disable flaky ROT remotes tests
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs
  appveyor.yml
Labels: area: tests, status: auto merge

#7769 Improve ScriptRunnerTests
  IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
Labels: area: tests

#7770 Adapt submodule button to context
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
Labels: status: auto merge

#7775 Fix incomplete reset in ReferenceRepository
  UnitTests/CommonTestUtils/ReferenceRepository.cs
Labels: area: tests

#7597 Improve restoring of the commit dialog geometry (Fixes #7588)
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/SplitterManager.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitUI.Tests/SplitterManagerTest.cs
Labels: status: auto merge

#7765 Improve exception-safety of UITests.RunForm
  IntegrationTests/UI.IntegrationTests/UITest.cs
Labels: area: tests

#7766 JoinPendingOperationsAsync right after closing the tested Form
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
  IntegrationTests/UI.IntegrationTests/UITest.cs
Labels: area: tests

#7781 Support merge.guitool
  GitCommands/Config/SettingKeyString.cs
  GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitVersion.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  UnitTests/GitCommands.Tests/DiffMergeTools/DiffMergeToolConfigurationManagerTests.cs
Labels: status: auto merge

#7779 SidePanel Submodules: Status for top module
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
Labels: status: auto merge

#7800 Stash: Form fail to load
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7818 Split CommitInfoTests into unit/integration tests
  IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
  UnitTests/GitUI.Tests/UserControls/CommitInfo/BranchComparerTests.cs
  UnitTests/GitUI.Tests/UserControls/CommitInfo/RefsFormatterTests.cs
  UnitTests/GitUI.Tests/UserControls/InteractiveGitActionControlTests.cs
Labels: area: tests

#7798 RevisionDiff: Try retain the file selection when switching commits
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
Labels: status: auto merge
