Repository gitextensions/gitextensions, pull requests merged in 2020-04, with the labels that each got.

#7929 Break the build if there are any errors in publish tasks
  GitExtensions/Project.Publish.targets
Labels: status: auto merge

#7932 Fix/7931
  GitCommands/PathUtil.cs
  GitUI/CommandsDialogs/FormClone.cs
  UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Labels: :pen: status: cla signed

#7922 FileStatus icon: submodule before status updated
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7948 fix: Locate diff tools in C:\Program Files\ folder
  GitCommands/PathUtil.cs
Labels: status: auto merge

#7951 Merge combined conflict set to IsConflict
  GitCommands/Git/GitModule.cs
Labels: status: auto merge

#7916 Prepopulate branch name in FormCreateBranch
  GitUI/CommandsDialogs/FormCreateBranch.cs
Labels: area: user experience, status: auto merge

#7955 Fix error during Publish build.
  contributors.txt
  scripts/tools/Publish.targets
Labels: :scroll: status: needs cla

#7926 Use ViewChangesAsync consistently for changes
  GitCommands/FileHelper.cs
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormLog.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/CommitDiff.cs
Labels: status: auto merge

#7961 Align context menu order for FileStatusList
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7976 GitStatusMonitor: Avoid background updates if GUI is not visible
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/Interops/User32/IsIconic.cs
Labels: status: auto merge

#7923 RevDiff: Show common/unique files for BASE->selected(B)
  GitCommands/Git/GitItemStatus.cs
  GitCommands/Git/GitItemStatusFileExtensionComparer.cs
  GitCommands/Git/GitItemStatusNameComparer.cs
  GitCommands/Git/GitItemStatusNameEqualityComparer.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7984 Deleted files presented as Unkown
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7888 Add hotkey for switching between artificial commits
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/ToggleBetweenArtificialAndHeadCommitsTests.cs
Labels: area: user experience, status: auto merge

#7993 Fix up show all branches / tags in history
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  ResourceManager/CommandEventArgs.cs
  ResourceManager/LinkFactory.cs
  UnitTests/ResourceManager.Tests/LinkFactoryFixture.cs
Labels: status: auto merge

#7694 Delete multiple files at a same time with popup menu
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/Translation/English.xlf
  ResourceManager/Strings.cs
  UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Labels: type: translation changed

#7490 OpenRemoteUrlInBrowser: Issue (#7439)
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/Globe.png
  GitUI/Translation/English.xlf
  contributors.txt
Labels: :pen: status: cla signed, type: translation changed

#8012 RevDiff, Commit: Delete untracked directories
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Labels: status: auto merge

#8015 Tweak commit hash of portable build
  GitExtensions/Project.Publish.targets
  appveyor.yml
Labels: area: scripting

#7981 Redesign script config
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.ScriptInfoProxy.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.resx
  GitUI/Design/ExecutableFileNameEditor.cs
  GitUI/Design/PropertyOrderAttribute.cs
  GitUI/Design/PropertySorter.cs
  GitUI/GitUI.csproj
  GitUI/Script/ScriptEvent.cs
  GitUI/Script/ScriptInfo.cs
  GitUI/Script/ScriptManager.cs
  GitUI/Themes/dark.css
  GitUI/Translation/English.xlf
Labels: type: translation changed

#8037 Apply dark theme for check boxes in NativeListView
  GitUI/Interops/DTBGOPTS.cs
  GitUI/Theming/Renderers/ListViewRenderer.cs
  GitUI/Theming/Renderers/ThemeRenderer.cs
  GitUI/Theming/Win32ThemeDelegates.cs
  GitUI/Theming/Win32ThemeHooks.cs
  GitUI/UserControls/NativeListView.cs
Labels: area: dark theme

#8040 Ignore Microsoft.WindowsAPICodePack.Shell.ShellException
  GitUI/WindowsJumpListManager.cs
Labels: status: auto merge

#8043 Ignore GitHub API rate limit induced errors when search for app updates
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
Labels: status: auto merge

#8042 Fix 3954 quotes in merge commit message
  GitCommands/CommitMessageManager.cs
  GitCommands/CommitMessageType.cs
  GitCommands/Git/GitCommandHelpers.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormMergeBranch.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
  UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
Labels: status: auto merge

#7899 RevDiff: Show common files for BASE->A
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormLog.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/CommitDiff.cs
  GitUI/UserControls/FileStatusItem.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/GitItemStatusWithParent.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs
  UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Labels: status: auto merge
