Repository gitextensions/gitextensions, pull requests merged in 2020-03, with the labels that each got.

#7824 revdiff: Show new file in worktree as file, not diff
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormLog.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/CommitDiff.cs
Labels: status: auto merge

#7685 Make folder removal safer
  GitCommands/PathUtil.cs
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/GitUICommands.cs
  GitUI/Strings.cs
  UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Labels: status: auto merge

#7820 Surround access to plugin collection with a `lock()`
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/Plugin/PluginRegistry.cs
  GitUI/Script/ScriptRunner.cs
Labels: status: auto merge

#7732 AzureDevOps CI: Fix and improvements
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
  Plugins/BuildServerIntegration/AzureDevOpsIntegration/Properties/AssemblyInfo.cs
  UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/AzureDevOpsAdapterTests.cs
Labels: status: auto merge

#7831 Show new files as file, not diff
  GitCommands/Patches/PatchManager.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
Labels: status: auto merge

#7767 Fix commit info tests
  IntegrationTests/UI.IntegrationTests/UITest.cs
  IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
Labels: area: tests

#7881 BitBucket plugin update of RestSharp
  Plugins/Bitbucket/ApprovePullRequest.cs
  Plugins/Bitbucket/Bitbucket.csproj
  Plugins/Bitbucket/BitbucketRequestBase.cs
  Plugins/Bitbucket/MergePullRequest.cs
Labels: status: auto merge

#7868 Display text if an image cannot be displayed
  GitUI/Editor/FileViewer.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge

#7893 Share common GitUI.Strings.Error
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
  GitUI/CommandsDialogs/BrowseDialog/MenuCommand.cs
  GitUI/CommandsDialogs/FormAddToGitIgnore.cs
  GitUI/CommandsDialogs/FormApplyPatch.cs
  GitUI/CommandsDialogs/FormArchive.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCherryPick.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormCreateTag.cs
  GitUI/CommandsDialogs/FormEditor.cs
  GitUI/CommandsDialogs/FormFormatPatch.cs
  GitUI/CommandsDialogs/FormInit.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRebase.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/FormRevertCommit.cs
  GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUICommands.cs
  GitUI/MessageBoxes.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/AvatarControl.cs
  GitUI/UserControls/BranchComboBox.cs
  GitUI/UserControls/CommitPickerSmallControl.cs
  GitUI/UserControls/PatchGrid.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Labels: status: auto merge

#7687 RevisionGrid: Directory Diff HotKey
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: auto merge

#7883 Add setting to show branch name in recent repos drop down
  GitCommands/Settings/AppSettings.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/Translation/English.xlf
Labels: :pen: status: cla signed

#7891 FormCommit: F3 to diff large files
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Labels: status: auto merge

#7908 Bugfix/i7898 nre no parent
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitRevisionTester.cs
  GitUI/CommandsDialogs/FormDiff.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/UserControls/FileStatusList.cs
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.cs
Labels: status: auto merge

#7904 Add root description to Git node in settings tree view
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.resx
  GitUI/Translation/English.xlf
  contributors.txt
Labels: :pen: status: cla signed

#7912 RevDiff: follow selection only in first list group
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/UserControls/FileStatusList.cs
Labels: status: auto merge

#7913 git-status: use config to set ignoreSubmodules
  GitCommands/Git/GitCommandHelpers.cs
  GitExtUtils/GitCommandConfiguration.cs
  UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge
