Repository gitextensions/gitextensions, pull requests merged in 2021-07, with the labels that each got.

#9330 Reduce window flicker and loss of focus
  GitUI/CommandsDialogs/FormRebase.Designer.cs
  GitUI/CommandsDialogs/FormRebase.cs
Labels: status: auto merge

#9243 RevisionReader: Parse raw commit body
  .gitattributes
  GitCommands/DateTimeUtils.cs
  GitCommands/Git/GitModule.cs
  GitCommands/GitCommands.csproj
  GitCommands/RevisionReader.cs
  GitCommands/StringPool.cs
  GitUI/CommandsDialogs/FormVerify.LostObject.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
  Packages.props
  Plugins/GitUIPluginInterfaces/GitRevision.cs
  Plugins/GitUIPluginInterfaces/ObjectId.cs
  UnitTests/GitCommands.Tests/GitCommands.Tests.csproj
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.multi_pathfilter.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.no_subject.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.normal.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.simple_pathfilter.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.subject_no_body.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.cs
  UnitTests/GitCommands.Tests/StringPoolTests.cs
  UnitTests/GitCommands.Tests/TestData/RevisionReader/bad_parentid.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/bad_parentid_length.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/bad_sha.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/empty.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/illegal_timestamp.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/multi_pathfilter.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/no_encoding.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/no_subject.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/normal.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/short_sha.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/simple_pathfilter.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/subject_no_body.bin
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs
Labels: status: auto merge

#9335 Browse: Advanced filter improvements
  GitCommands/RevisionReader.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/FunnelPencil.png
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Labels: status: auto merge

#9107 Start using MEF
  GitCommands/AppTitleGenerator.cs
  GitCommands/Git/GitDirectoryResolver.cs
  GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
  GitExtensions/Program.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Script/ScriptOptionsParser.cs
  GitUI/WindowsJumpListManager.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.ReorderNodes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockAppTitleGenerator.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockRepositoryDescriptionProvider.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockWindowsJumpListManager.cs
  Packages.props
  Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/CommonTestUtils/MEF/ExportProviderCache.Scope.cs
  UnitTests/CommonTestUtils/MEF/ExportProviderCache.SimpleAssemblyLoader.cs
  UnitTests/CommonTestUtils/MEF/ExportProviderCache.SingleExportProviderFactory.cs
  UnitTests/CommonTestUtils/MEF/ExportProviderCache.cs
  UnitTests/CommonTestUtils/MEF/TestComposition.Hash.cs
  UnitTests/CommonTestUtils/MEF/TestComposition.cs
  UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
  UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Labels: status: auto merge

#9336 Preparations for exceptions on git error (part 4 of 4)
  GitCommands/Git/ExecutableExtensions.cs
  GitCommands/Git/GitModule.cs
Labels: type: discussion

#9359 Log RevisionReader parse errors
  GitCommands/RevisionReader.cs
  Plugins/GitUIPluginInterfaces/ObjectId.cs
  UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Labels: status: auto merge

#9385 Do not check if path exists before settings GIT_SSH
  GitCommands/Git/GitSshHelpers.cs
Labels: :mailbox_with_no_mail: needs: author feedback

#8956 Dialogs layout alignment - `FormDeleteBranch`
  GitCommands/Git/Commands/GitDeleteBranchCmd.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/CommandsDialogs/FormDeleteBranch.Designer.cs
  GitUI/CommandsDialogs/FormDeleteBranch.cs
  GitUI/CommandsDialogs/FormDeleteBranch.resx
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
  GitUI/GitUICommands.cs
  GitUI/TranslatedStrings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/BranchComboBox.Designer.cs
  UnitTests/GitCommands.Tests/Git/Commands/GitDeleteBranchCmdTests.cs
Labels: status: auto merge
