Repository gitextensions/gitextensions, pull requests merged in 2021-11, with the labels that each got.

#9687 Change Revision Links separator (#9668)
  GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
  UnitTests/GitUI.Tests/Editor/RichTextBoxXhtmlSupportExtensionTests.cs
Labels: :pen: status: cla signed, hacktoberfest-accepted

#9704 Generate .NET installer
  Directory.Build.props
  GitExtensions/GitExtensions.csproj
  GitExtensions/Project.Publish.targets
  GitExtensions/app.config
  Packages.props
  Setup/Config.wxi
  Setup/EnableUpgrades.wxi
  Setup/Product.wxs
  appveyor.yml
  scripts/native.proj
Labels: area: installer, area: toolchain

#9747 Fix tests
  GitCommands/Settings/AppSettings.cs
Labels: area: tests
