Repository gitextensions/gitextensions, pull requests merged in 2021-02, with the labels that each got.

#8801 Fix filter by branch with globbing characters *?[]
  GitCommands/RevisionReader.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: area: filters

#8682 A variety of accessibility-related fixes for the contents of the main pane on the Config page
  GitExtensions/app.config
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
  GitUI/Translation/English.xlf
  contributors.txt
Labels: :pen: status: cla signed, area: accessibility

#8826 Restore/expose IGitUICommands.StartRemotesDialog
  GitUI/GitUICommands.cs
  Plugins/GitUIPluginInterfaces/IGitUICommands.cs
Labels: area: plugins

#8833 Jenkins: requery new running jobs
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
Labels: status: auto merge

#8830 AppVeyor: Handle v2 tokens
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/AppVeyorAdapterTests.cs
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_master_build.approved.txt
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt
Labels: status: auto merge

#8700 Custom difftool in RevDiff, FileHistory, Commit, RevGrid
  GitCommands/CustomDiffMergeTool.cs
  GitCommands/CustomDiffMergeToolCache.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
  GitUI/CustomDiffMergeToolProvider.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
  ResourceManager/Strings.cs
  UnitTests/GitCommands.Tests/CustomDiffMergeToolCacheTests.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge, type: translation changed

#8858 3.5 Custom difftool in RevDiff, FileHistory, Commit, RevGrid
  GitCommands/CustomDiffMergeTool.cs
  GitCommands/CustomDiffMergeToolCache.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormFileHistory.Designer.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
  GitUI/CustomDiffMergeToolProvider.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
  ResourceManager/Strings.cs
  UnitTests/GitCommands.Tests/CustomDiffMergeToolCacheTests.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: type: translation changed

#8761 Change TextImageRelation For "Reset All" Button
  GitUI/CommandsDialogs/FormCommit.Designer.cs
Labels: :pen: status: cla signed, area: translation

#8845 Notify of repo changes when unused branches were deleted
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
  contributors.txt
Labels: :pen: status: cla signed, area: plugins

#8854 Browse: Avoid extra git-rev-parse at start
  GitCommands/Git/GitModule.cs
  GitCommands/Git/SubmoduleHelpers.cs
  GitUI/GitUIExtensions.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: auto merge

#8866 Cache Git commands related to submodules
  GitCommands/CommitDataManager.cs
  GitCommands/Git/CommandCache.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/SubmoduleHelpers.cs
  GitUI/Editor/FileViewer.cs
  ResourceManager/LocalizationHelpers.cs
Labels: status: auto merge

#8875 Remove double execution of GetSubmoduleStatusAsync
  GitUI/GitUIExtensions.cs
Labels: :mailbox_with_no_mail: needs: author feedback, status: auto merge

#8887 Eliminate closure allocations
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Labels: status: auto merge

#8867 Submodule SidePanel updated too often
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
Labels: status: auto merge
