Repository gitextensions/gitextensions, pull requests merged in 2021-01, with the labels that each got.

#8713 TranslationApp: Include "AccessibleName"
  ResourceManager/Xliff/TranslationUtil.cs
Labels: accessibility

#8667 Left panel enhancement
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/BranchTreePanel/RepoObjectsTree.resx
  GitUI/CommandsDialogs/SearchControl.Designer.cs
  GitUI/CommandsDialogs/SearchControl.cs
  GitUI/Interops/Messages.cs
  GitUI/Interops/User32/GetWindowDC.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/TextBoxEx.cs
Labels: area: left-panel

#8716 Fix high CPU usage of TeamCityAdapter
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  contributors.txt
Labels: :pen: status: cla signed, status: auto merge

#8708 FileViewer: Consistently use Stage/Reset Lines
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Strings.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge, type: discussion

#8721 Process.Start with ExternalOperationException
  GitCommands/Git/Executable.cs
  GitExtensions/Program.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
  GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
  GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
  GitUI/CommandsDialogs/FormAbout.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormGitIgnore.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
  GitUI/HelperDialogs/FormResetCurrentBranch.cs
  GitUI/NBugReports/BugReportForm.cs
  GitUI/OsShellUtil.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/UserControls/AvatarControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  Plugins/GitUIPluginInterfaces/IExecutable.cs
  UnitTests/CommonTestUtils/MockExecutable.cs
Labels: status: auto merge

#8703 Submodule browse: Select both first/second commits
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommandlineHelp.resx
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/GitUICommands.cs
  GitUI/HelperDialogs/FormChooseCommit.cs
  GitUI/UserControls/FileStatusList.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
Labels: status: auto merge

#8727 ResolveConflicts: Incorrect evaluation of mergetool path
  GitCommands/PathUtil.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
Labels: status: auto merge

#8731 StageAll and UnstageAll improvement when Filter active #8596
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/StageAllFiltered.png
  GitUI/Resources/Icons/UnstageAllFiltered.png
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusList.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  UnitTests/CommonTestUtils/ReferenceRepository.cs
Labels: :pen: status: cla signed, status: auto merge

#7825 RevisionDiff: Stage/Unstage selected lines
  GitCommands/Git/GitModule.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionDiffController.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUIExtensions.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  UnitTests/GitUI.Tests/Editor/FileViewerTextTests.cs
Labels: status: auto merge

#8736 fix crash on refresh when submodule nodes selected
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Labels: status: auto merge

#8775 Pass 'skip' parameter
  GitExtUtils/GitUI/ControlUtil.cs
Labels: status: auto merge

#8772 Improve build times
  GitUI/GitUI.csproj
  UnitTests/GitCommands.Tests/GitCommands.Tests.csproj
  UnitTests/Plugins/GitUIPluginInterfaces.Tests/GitUIPluginInterfaces.Tests.csproj
Labels: status: auto merge

#8737 C#9 pattern enhancements
  GitCommands/Git/GitBranchNameNormaliser.cs
  GitCommands/Git/GitItemStatus.cs
  GitCommands/Git/GitModule.cs
  GitCommands/StringPool.cs
  GitCommands/Utils/WeakRefCache.cs
  GitExtUtils/GitUI/Theming/Theme.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitUICommands.cs
  GitUI/Interops/UxTheme/SetWindowTheme.cs
  GitUI/MouseWheelRedirector.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/Script/SplitButton.cs
  GitUI/SpellChecker/EditNetSpell.cs
  GitUI/UserControls/InteractiveGitActionControl.cs
  GitUI/UserControls/NativeTreeViewDoubleClickDecorator.cs
  GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  Plugins/Statistics/GitStatistics/PieChart/EdgeColor.cs
  Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
  Plugins/Statistics/GitStatistics/PieChart/PieSlice.cs
  ResourceManager/GitExtensionsControl.cs
  Solution.Versions.props
  UnitTests/GitCommands.Tests/Git/GitBranchNameNormaliserTest.cs
Labels: status: auto merge

#8776 Annotate GitExtUtils project
  GitCommands/AppTitleGenerator.cs
  GitCommands/Config/ConfigFile.cs
  GitCommands/Config/ConfigSection.cs
  GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
  GitCommands/DiffMergeTools/VsDiffMerge.cs
  GitCommands/EnvironmentPathsProvider.cs
  GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs
  GitCommands/FileAssociatedIconProvider.cs
  GitCommands/FullPathResolver.cs
  GitCommands/Git/CommandCache.cs
  GitCommands/Git/GitBranchNameNormaliser.cs
  GitCommands/Git/GitBranchNameOptions.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitPushAction.cs
  GitCommands/Git/GitRevisionSummaryBuilder.cs
  GitCommands/Git/GitSshHelpers.cs
  GitCommands/Git/GitTreeParser.cs
  GitCommands/Git/SubmoduleHelpers.cs
  GitCommands/GitCommands.csproj
  GitCommands/Patches/PatchProcessor.cs
  GitCommands/PathUtil.cs
  GitCommands/Settings/ConfigFileSettings.cs
  GitCommands/StringExtensions.cs
  GitCommands/Submodules/SubmoduleStatusProvider.cs
  GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
  GitCommands/Utils/EnvUtils.cs
  GitExtUtils/Annotations.cs
  GitExtUtils/ArgumentBuilder.cs
  GitExtUtils/ArgumentString.cs
  GitExtUtils/ArrayExtensions.cs
  GitExtUtils/ClipboardUtil.cs
  GitExtUtils/GitArgumentBuilder.cs
  GitExtUtils/GitCommandConfiguration.cs
  GitExtUtils/GitExtUtils.csproj
  GitExtUtils/GitUI/CancellationTokenSequence.cs
  GitExtUtils/GitUI/ControlDpiExtensions.cs
  GitExtUtils/GitUI/ControlHotkeyExtensions.cs
  GitExtUtils/GitUI/ControlTagExtensions.cs
  GitExtUtils/GitUI/ControlThreadingExtensions.cs
  GitExtUtils/GitUI/ControlUtil.cs
  GitExtUtils/GitUI/HighDpiMouseCursors.cs
  GitExtUtils/GitUI/ListViewExtensions.cs
  GitExtUtils/GitUI/Theming/BmpTransformation.cs
  GitExtUtils/GitUI/Theming/ColorHelper.cs
  GitExtUtils/GitUI/Theming/LightnessCorrection.cs
  GitExtUtils/GitUI/Theming/TabControlPaintContext.cs
  GitExtUtils/GitUI/Theming/Theme.cs
  GitExtUtils/GitUI/Theming/ThemeId.cs
  GitExtUtils/GitUI/Theming/ThemeSettings.cs
  GitExtUtils/GitUI/ThreadHelper.cs
  GitExtUtils/MruCache.cs
  GitExtUtils/StringBuilderExtensions.cs
  GitExtUtils/Strings.cs
  GitExtensions/Program.cs
Labels: status: auto merge

#8774 Add mnemonics to RevisionGrid context menu
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Labels: area: accessibility, area: user experience

#8787 Add test accessors borrowed from https://github.com/dotnet/winforms/
  GitUI/GitExtensionsForm.cs
  UnitTests/CommonTestUtils/ITestAccessor.cs
  UnitTests/CommonTestUtils/TestAccessor.cs
  UnitTests/CommonTestUtils/TestAccessors.cs
  UnitTests/GitUI.Tests/GitExtensionsFormTests.cs
Labels: area: tests

#8791 Pull down latest Transifex translations with 75% bar
  GitUI/Translation/Czech.xlf
  GitUI/Translation/Dutch.xlf
  GitUI/Translation/French.xlf
  GitUI/Translation/German.xlf
  GitUI/Translation/Italian.xlf
  GitUI/Translation/Japanese.Plugins.xlf
  GitUI/Translation/Japanese.xlf
  GitUI/Translation/Korean.xlf
  GitUI/Translation/Latvian.xlf
  GitUI/Translation/Polish.xlf
  GitUI/Translation/Portuguese (Brazil).Plugins.xlf
  GitUI/Translation/Russian.xlf
  GitUI/Translation/Simplified Chinese.Plugins.xlf
  GitUI/Translation/Simplified Chinese.xlf
  GitUI/Translation/Spanish (Argentina).xlf
  GitUI/Translation/Spanish.xlf
  GitUI/Translation/en_pseudo.Plugins.xlf
  GitUI/Translation/en_pseudo.xlf
  Setup/Product.wxs
Labels: area: translation

#8786 Update open directory
  GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
  contributors.txt
Labels: :pen: status: cla signed, status: auto merge
