Repository gitextensions/gitextensions, pull requests merged in 2021-06, with the labels that each got.

#9246 Use static/cached GitVersion to resolve Git path
  GitCommands/Git/GitVersion.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
Labels: status: auto merge

#9264 Enable CA1416: Validate platform compatibility
  .editorconfig
  CommonAssemblyInfo.cs
  Directory.Build.props
  UnitTests/GitCommands.Tests/Properties/AssemblyInfo.cs
  UnitTests/GitExtUtils.Tests/Properties/AssemblyInfo.cs
  UnitTests/GitUI.Tests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/DeleteUnusedBranches.Tests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/GitUIPluginInterfaces.Tests/Properties/AssemblyInfo.cs
  UnitTests/Plugins/ReleaseNotesGenerator.Tests/Properties/AssemblyInfo.cs
  UnitTests/ResourceManager.Tests/Properties/AssemblyInfo.cs
Labels: .NET migration

#9268 Allow rollForward for .NET 5.0 SDK version
  global.json
Labels: area: toolchain

#9282 Add mnemonics to frequently used dialogs
  GitUI/CommandsDialogs/FormCheckoutRevision.Designer.cs
  GitUI/CommandsDialogs/FormCherryPick.Designer.cs
  GitUI/CommandsDialogs/FormPush.Designer.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRevertCommit.Designer.cs
  GitUI/Translation/English.xlf
Labels: area: user experience

#9285 Add mnemonics to context menu of `RevisionDiffControl`
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/TranslatedStrings.cs
  GitUI/Translation/English.xlf
Labels: area: user experience

#9301 Make showing commit message body in the revision graph optional
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  contributors.txt
Labels: :pen: status: cla signed

#9286 Fixup partial graph rendering
  GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: status: auto merge

#9308 Stash: Keyboard navigation
  GitUI/CommandsDialogs/FormStash.Designer.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
Labels: status: auto merge
