Repository gitextensions/gitextensions, pull requests merged in 2021-04, with the labels that each got.

#8903 Graph: Ensure branch colors are not equal to branchs they are merged to
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/LaneInfo.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: :eyeglasses: status: needs review, area: user experience, status: auto merge

#8971 Support Bitbucket repos with dots in the name
  Plugins/Bitbucket/Settings.cs
  contributors.txt
Labels: :pen: status: cla signed

#9057 rev-parse should use --quiet --verify
  GitCommands/Git/GitModule.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge

#9060 Suppress "Theme not found" if setting is empty
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
Labels: :beetle: type: bug, area: settings, area: user experience, status: auto merge

#9064 Do not reset a valid `AppSettings.GitBinDir`
  GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
  UnitTests/GitCommands.Tests/Git/ExecutableExtensionsTests.cs
Labels: :beetle: type: bug, area: settings

#9058 AutoComplete: Avoid Git for non tracked files
  GitCommands/Git/GitModule.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Labels: status: auto merge

#9059 Use exit status instead of IsGitErrorMessage()
  GitCommands/CommitDataManager.cs
  GitCommands/Git/ExecutableExtensions.cs
  GitCommands/Git/GitModule.cs
  ResourceManager/LocalizationHelpers.cs
Labels: status: auto merge

#9050 Straighten graph lanes over multiple rows
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphRowTests.cs
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Labels: area: user experience

#9087 FormCommitDiff cannot handle artificial commits
  GitUI/UserControls/PatchGrid.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: status: auto merge

#9097 Reduce allocations for RevisionGraph lane straightening
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
Labels: status: auto merge

#9072 GitHub token: Add a link to let the user generate its Personal Access Token
  Plugins/GitHub3/GitHub3Plugin.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.Designer.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.resx
Labels: status: auto merge

#9103 (v3.5) GitHub token: Add a link to let the user generate its Personal Access Token
  Plugins/GitHub3/GitHub3Plugin.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.Designer.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.cs
  Plugins/GitHub3/GitHubCredentialsPrompt.resx
Labels: type: translation changed

#9114 Let installer not activate disabled telemetry
  Bin/set-telemetry.ps1
Labels: area: installer

#9124 Install `Newtonsoft.Json.dll` not only for plugins
  Setup/Product.wxs
Labels: area: installer

#9123 Let installer not activate disabled telemetry
  Bin/set-telemetry.ps1
Labels: area: installer

#9130 Quote path for opening with `Explorer.exe`
  GitUI/OsShellUtil.cs
Labels: status: auto merge
