Repository gitextensions/gitextensions, pull requests merged in 2021-05, with the labels that each got.

#9132 Sanitize localized stack trace in exception tests
  UnitTests/BugReporter.Tests/SerializableExceptionTests.cs
Labels: area: tests

#9136 Update README
  README.md
Labels: status: auto merge

#9082 Fix settings saving for "Detailed" section by selected setting source
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/BuildServerSettings.cs
  GitCommands/Settings/DetachedServerSettings.cs
  GitCommands/Settings/DetailedSettings.cs
  GitCommands/Settings/RepoDistSettings.cs
  GitCommands/Settings/SettingsSourceExtension.cs
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
  GitUI/CommandsDialogs/FormMergeBranch.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/SettingsDialog/AutoLayoutSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DetailedSettingsPage.cs
  GitUI/SpellChecker/EditNetSpell.cs
  GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
  Plugins/GitUIPluginInterfaces/Settings/IBuildServerSettings.cs
  Plugins/GitUIPluginInterfaces/Settings/IDetachedSettings.cs
  Plugins/GitUIPluginInterfaces/Settings/IDetailedSettings.cs
Labels: area: settings

#9167 Add `BugReporter.exe` to installer
  Setup/Product.wxs
Labels: area: installer

#9145 Stash pop/apply: Refresh grid if command was successful
  GitUI/GitUICommands.cs
Labels: status: auto merge

#9140 feat: add dot command to GitUICommands
  GitUI/CommandsDialogs/FormCommandlineHelp.resx
  GitUI/GitUICommands.cs
Labels: :pen: status: cla signed

#9196 Do not try to show deleted images in diffviewer
  GitUI/GitUIExtensions.cs
Labels: status: auto merge

#9197 Diff/Commit: Do not show Open for deleted items
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
Labels: status: auto merge

#9182 Set GIT_SSH only if path exists
  GitCommands/Git/GitSshHelpers.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
Labels: status: auto merge

#9203 LogCaptureCallStacks in AppSettings
  GitCommands/Logging/CommandLog.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
Labels: status: auto merge

#9188 Keep persistent ssh settings in registry
  GitCommands/Git/GitSshHelpers.cs
  GitCommands/Settings/AppSettings.cs
  GitCommands/SshPathLocator.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
  GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs
  UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
Labels: status: auto merge

#9206 Use enum interface for GetRefs()
  GitCommands/Git/Commands/GitCommandHelpers.cs
  GitCommands/Git/Commands/GitRefsEnum.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
  GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCheckoutBranch.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormDeleteBranch.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
  GitUI/CommandsDialogs/FormDeleteTag.cs
  GitUI/CommandsDialogs/FormMergeBranch.cs
  GitUI/CommandsDialogs/FormPull.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormRebase.cs
  GitUI/CommandsDialogs/FormReflog.cs
  GitUI/CommandsDialogs/FormRemotes.cs
  GitUI/CommandsDialogs/FormVerify.cs
  GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
  GitUI/FilterBranchHelper.cs
  GitUI/HelperDialogs/FormResetAnotherBranch.cs
  GitUI/UserControls/BranchSelector.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  Plugins/GitUIPluginInterfaces/RefsFilter.cs
  UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
  UnitTests/GitCommands.Tests/Remote/ConfigFileRemoteSettingsManagerTests.cs
Labels: status: auto merge

#9226 Improve RevisionGridControlTests
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Labels: area: tests

#9217 Replace PathUtil.Combine and GetExtension with Path.
  GitCommands/FileAssociatedIconProvider.cs
  GitCommands/FullPathResolver.cs
  GitCommands/Git/GitItemStatusFileExtensionComparer.cs
  GitCommands/GitRevisionInfoProvider.cs
  GitCommands/PathUtil.cs
  GitCommands/Settings/FileSettingsCache.cs
  GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeController.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPageController.cs
  GitUI/Editor/FileViewer.cs
  Plugins/Statistics/GitStatistics/LineCounter.cs
  UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Labels: status: auto merge

#8996 Small bits
  GitCommands/CommitMessageManager.cs
  GitCommands/CustomDiffMergeToolCache.cs
  GitCommands/ExternalLinks/ExternalLinksStorage.cs
  GitCommands/Git/Commands/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitCommands/StringPool.cs
  GitExtensions.sln.DotSettings
  GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Infrastructure/Telemetry/DiagnosticsClient.cs
  TranslationApp/Program.cs
Labels: status: auto merge

#9222 Git commands should never have colors
  GitCommands/Git/AheadBehindDataProvider.cs
  GitCommands/Git/Commands/GitCommandHelpers.cs
  GitCommands/Git/GitModule.cs
  GitExtUtils/GitCommandConfiguration.cs
  GitExtensions/AutoCompleteRegexes.txt
  GitUI/Editor/FileViewer.cs
  UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
Labels: status: auto merge

#9184 Restore build pipeline
  BugReporter/BugReporter.csproj
  Directory.Build.props
  Directory.Build.targets
  Externals/Directory.Build.props
  GitExtSshAskPass/SshAskPass.vcxproj
  GitExtensions.sln
  GitExtensions/GitExtensions.csproj
  GitExtensions/Project.Build.targets
  GitExtensions/Project.Loc.targets
  GitExtensions/Project.Publish.targets
  GitExtensionsShellEx/GitExtensionsShellEx.vcxproj
  GitUI/Translation/English.xlf
  IntegrationTests/Directory.Build.props
  Plugins/Directory.Build.props
  Setup/Setup.wixproj
  UnitTests/CommonTestUtils/CommonTestUtils.csproj
  UnitTests/CommonTestUtils/Properties/AssemblyInfo.cs
  UnitTests/Directory.Build.props
  UnitTests/Tests.targets
  appveyor.yml
  scripts/Localisation.targets
  scripts/Publish.targets
  scripts/RepoLayout.props
  scripts/Tests.props
  scripts/Tests.targets
  scripts/build.ps1
  scripts/native.proj
  scripts/pipeline-logging-functions.ps1
  scripts/sdk/Sdk.props
  scripts/sdk/Sdk.targets
  scripts/tools.ps1
  scripts/tools/AfterSolutionBuild.proj
  scripts/tools/Build.proj
  scripts/tools/BuildStep.props
  scripts/tools/Imports.targets
  scripts/tools/NUnit/NUnit.props
  scripts/tools/NUnit/NUnit.targets
  scripts/tools/ProjectDefaults.props
  scripts/tools/ProjectDefaults.targets
  scripts/tools/ProjectLayout.props
  scripts/tools/RepoLayout.props
  scripts/tools/Settings.props
  scripts/tools/Tests.props
  scripts/tools/Tests.targets
  scripts/tools/Version.targets
Labels: .NET migration, area: cli, area: installer, area: tests, area: toolchain
