Repository gitextensions/gitextensions, pull requests merged in 2021-03, with the labels that each got.

#8894 RevDiff: Request GitStatus updates at file manipulations
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Labels: status: auto merge

#8932 Focus ComboBox Branches of FormResetAnotherBranch
  GitUI/HelperDialogs/FormResetAnotherBranch.cs
Labels: area: user experience

#8883 Use pattern matching
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommitInfo/CommitInfo.cs
  GitUI/CommitInfo/CommitInfoHeader.cs
Labels: status: auto merge

#8925 Remove IExecutable.GetOutput
  GitCommands/Git/Executable.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  Plugins/GitUIPluginInterfaces/IExecutable.cs
  UnitTests/CommonTestUtils/MockExecutable.cs
  UnitTests/GitCommands.Tests/Git/Gpg/GitGpgControllerTests.cs
  UnitTests/GitUI.Tests/CommandsDialogs/FormAddSubmoduleTests.cs
Labels: status: auto merge

#8937 Fix invalid XML in DotSettings file
  GitExtensions.sln.DotSettings
Labels: status: auto merge

#8874 Left panel: Make "Expand all" and "Collapse all" based on selected node
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/Translation/English.xlf
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
Labels: type: discussion, type: translation changed

#8900 Add branch rendering improvements
  GitExtUtils/GitUI/Theming/AppColorDefaults.cs
  GitUI/Themes/invariant.css
  GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs
Labels: area: theming, area: user experience

#8950 Disable CodeCov integration
  scripts/tools/NUnit/NUnit.targets
Labels: area: tests

#8949 Stop loading custom diff tools during tests
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.ReorderNodes.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
  Plugins/GitUIPluginInterfaces/Settings/PseudoSetting.cs
Labels: area: tests

#8954 Remove return value from AsyncLoader
  GitCommands/AsyncLoader.cs
Labels: status: auto merge

#8849 Add borders in Commit Form and set splitter width like in VS
  GitExtUtils/GitUI/ControlDpiExtensions.cs
  GitUI/CommandsDialogs/FormBrowse.Designer.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/SplitterManager.cs
  UnitTests/GitUI.Tests/SplitterManagerTest.cs
Labels: :grey_exclamation: priority: high

#8959 Remove redundant await
  GitUI/Editor/FileViewer.cs
Labels: status: auto merge

#8967 Fix invalid null value assertion in plugin code
  Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
  Plugins/GitUIPluginInterfaces/PluginsPathScanner.cs
Labels: status: auto merge

#8973 Remove redundant suppressions
  GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
  GitCommands/Settings/AutoCRLFType.cs
  GitCommands/Settings/FileSettingsCache.cs
  GitExtUtils/GitUI/ControlThreadingExtensions.cs
  GitExtUtils/GitUI/HighDpiMouseCursors.cs
  GitExtUtils/GitUI/ThreadHelper.cs
  GitUI/BuildServerIntegration/BuildServerWatcher.cs
  GitUI/CommandsDialogs/FullBleedTabControl.cs
  GitUI/Editor/FileViewer.cs
  GitUI/GitModuleForm.cs
  GitUI/GitUICommands.cs
  GitUI/MouseWheelRedirector.cs
  GitUI/UserControls/MainThreadScheduler.cs
  GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
  Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
  ResourceManager/Strings.cs
  UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
  UnitTests/GitCommands.Tests/Git/ObjectIdTests.cs
  UnitTests/GitUI.Tests/CancellationTokenSequenceTests.cs
  UnitTests/GitUI.Tests/CommandsDialogs/RevisionFileTreeControllerTests.cs
  UnitTests/GitUI.Tests/ControlThreadingExtensionsTests.cs
Labels: status: auto merge

#8975 Move GitStatistics plugin to "GitExtensions.Plugins" namespace
  GitExtensions.sln
  Plugins/Statistics/GitStatistics/CodeFile.cs
  Plugins/Statistics/GitStatistics/FormGitStatistics.Designer.cs
  Plugins/Statistics/GitStatistics/FormGitStatistics.cs
  Plugins/Statistics/GitStatistics/GitExtensions.Plugins.GitStatistics.csproj
  Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
  Plugins/Statistics/GitStatistics/LineCounter.cs
  Plugins/Statistics/GitStatistics/PieChart/ColorUtil.cs
  Plugins/Statistics/GitStatistics/PieChart/EdgeColor.cs
  Plugins/Statistics/GitStatistics/PieChart/EdgeColorType.cs
  Plugins/Statistics/GitStatistics/PieChart/GraphicsUtil.cs
  Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
  Plugins/Statistics/GitStatistics/PieChart/PieChartControl.cs
  Plugins/Statistics/GitStatistics/PieChart/PieSlice.cs
  Plugins/Statistics/GitStatistics/PieChart/Quadrilateral.cs
  Plugins/Statistics/GitStatistics/PieChart/ShadowStyle.cs
  Plugins/Statistics/GitStatistics/PieChart/SliceSelectedArgs.cs
  Plugins/Statistics/GitStatistics/Properties/Resources.Designer.cs
  Setup/Product.wxs
Labels: area: plugins

#8981 Move GitImpact plugin to "GitExtensions.Plugins" namespace
  GitExtensions.sln
  Plugins/Statistics/GitImpact/FormImpact.Designer.cs
  Plugins/Statistics/GitImpact/FormImpact.cs
  Plugins/Statistics/GitImpact/GitExtensions.Plugins.GitImpact.csproj
  Plugins/Statistics/GitImpact/GitImpactPlugin.cs
  Plugins/Statistics/GitImpact/ImpactControl.cs
  Plugins/Statistics/GitImpact/Properties/Resources.Designer.cs
  Plugins/Statistics/GitStatistics/GitExtensions.Plugins.GitStatistics.csproj
  Plugins/Statistics/GitStatistics/Properties/Resources.Designer.cs
  Setup/Product.wxs
Labels: area: plugins

#8836 Jira plugin configuration - Password renamed to Password/API token
  Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.Designer.cs
Labels: :mailbox_with_no_mail: needs: author feedback, :zzz: status: no recent activity, type: translation changed

#8982 Move AutoCompileSubmodules plugin to "GitExtensions.Plugins" namespace
  GitExtensions.sln
  Plugins/AutoCompileSubmodules/AutoCompileSubModulesPlugin.cs
  Plugins/AutoCompileSubmodules/GitExtensions.Plugins.AutoCompileSubmodules.csproj
  Plugins/AutoCompileSubmodules/Properties/Resources.Designer.cs
  Setup/Product.wxs
Labels: area: plugins

#8983 Move BackgroundFetch plugin to "GitExtensions.Plugins" namespace
  GitExtensions.sln
  Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
  Plugins/BackgroundFetch/GitExtensions.Plugins.BackgroundFetch.csproj
  Plugins/BackgroundFetch/Properties/Resources.Designer.cs
  Setup/Product.wxs
Labels: area: plugins

#8993 Move ImpactLoader.cs from GitCommands.Statistics to GitExtensions.Plugins.GitImpact
  Plugins/Statistics/GitImpact/FormImpact.cs
  Plugins/Statistics/GitImpact/GitExtensions.Plugins.GitImpact.csproj
  Plugins/Statistics/GitImpact/ImpactControl.cs
  Plugins/Statistics/GitImpact/ImpactLoader.cs
Labels: area: plugins

#9001 Check BeforeCommit script failure to abort commit
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Script/ScriptManager.cs
  GitUI/Script/ScriptRunner.cs
Labels: :pen: status: cla signed

#9008 Push from empty FormCommit
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/FormPush.Designer.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/TranslatedStrings.cs
  GitUI/Translation/English.xlf
  ResourceManager/TranslatedStrings.cs
Labels: type: translation changed

#9009 FormBisect: Autosize form to prevent content to be clipped
  GitUI/CommandsDialogs/BrowseDialog/FormBisect.Designer.cs
  GitUI/Translation/English.xlf
Labels: area: hdpi

#9025 Update UI only after save settings
  GitUI/CommandsDialogs/FormSettings.cs
  GitUI/GitUICommands.cs
Labels: area: settings

#8995 Resolve PluginSettings key names issue
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
  GitUI/CommandsDialogs/SettingsDialog/Plugins/PluginSettingsPage.cs
  GitUI/Plugin/GitPluginSettingsContainer.cs
  GitUI/Plugin/PluginRegistry.cs
  GitUI/Script/ScriptRunner.cs
  GitUI/Translation/Czech.Plugins.xlf
  GitUI/Translation/Dutch.Plugins.xlf
  GitUI/Translation/English.Plugins.xlf
  GitUI/Translation/French.Plugins.xlf
  GitUI/Translation/German.Plugins.xlf
  GitUI/Translation/Japanese.Plugins.xlf
  GitUI/Translation/Polish.Plugins.xlf
  GitUI/Translation/Russian.Plugins.xlf
  GitUI/Translation/Simplified Chinese.Plugins.xlf
  GitUI/Translation/Spanish.Plugins.xlf
  GitUI/Translation/en_pseudo.Plugins.xlf
  Plugins/AutoCompileSubmodules/AutoCompileSubModulesPlugin.cs
  Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
  Plugins/Bitbucket/BitbucketPlugin.cs
  Plugins/CreateLocalBranches/CreateLocalBranchesPlugin.cs
  Plugins/DeleteUnusedBranches/DeleteUnusedBranchesPlugin.cs
  Plugins/FindLargeFiles/FindLargeFilesPlugin.cs
  Plugins/GitFlow/GitFlowPlugin.cs
  Plugins/GitHub3/GitHub3Plugin.cs
  Plugins/GitUIPluginInterfaces/IGitPlugin.cs
  Plugins/Gource/GourcePlugin.cs
  Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
  Plugins/ProxySwitcher/ProxySwitcherPlugin.cs
  Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorPlugin.cs
  Plugins/Statistics/GitImpact/GitImpactPlugin.cs
  Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
  ResourceManager/GitPluginBase.cs
Labels: area: plugins

#9040 Remove unused memory settings
  GitCommands/Settings/MemorySettings.cs
  GitCommands/Settings/MemorySettingsCache.cs
Labels: area: settings

#9038 Improve display of exceptions
  GitUI/NBugReports/BugReportForm.Designer.cs
  GitUI/NBugReports/BugReportForm.cs
  GitUI/NBugReports/BugReporter.cs
  GitUI/TranslatedStrings.cs
  GitUI/Translation/English.xlf
  UnitTests/GitUI.Tests/NBugReports/BugReporterTests.cs
Labels: status: auto merge

#9039 Remove redundant creation of settings container
  GitCommands/ExternalLinks/ExternalLinksStorage.cs
Labels: area: settings

#9037 Handle errors accessing the amend state file
  GitCommands/CommitMessageManager.cs
  UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
Labels: status: auto merge

#9028 Straighten graph lanes
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
  UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphRowTests.cs
Labels: area: user experience, status: auto merge
