Repository gitextensions/gitextensions, pull requests merged in 2021-08, with the labels that each got.

#9461 Stabilise RevisionGridControl filtering tests
  GitCommands/Settings/AppSettings.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/Infrastructure/Telemetry/FormBrowseDiagnosticsReporter.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
  UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Labels: area: tests

#9478 Takes 2 at trying to fix failing tests
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Labels: area: tests

#9380 Recent repo search
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
  GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
  GitUI/Translation/English.xlf
Labels: :pen: status: cla signed

#8709 Implemented F2 rename branch in RepoObjectsTree.
  GitUI/BranchTreePanel/ContextMenu/MenuItemsGenerator.cs
  GitUI/BranchTreePanel/RepoObjectsTree.LocalBranchNode.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
Labels: :pen: status: cla signed

#8957 Dialogs layout alignment - `FormDeleteRemoteBranch`
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.Designer.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
  GitUI/CommandsDialogs/FormDeleteRemoteBranch.resx
  GitUI/Translation/English.xlf
Labels: status: auto merge
