Repository gitextensions/gitextensions, pull requests merged in 2021-10, with the labels that each got.

#9607 Stabilise left panel tests
  GitCommands/Git/ExecutableExtensions.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
Labels: hacktoberfest-accepted

#9555 Allow hiding stash references on revision grid
  GitCommands/RevisionReader.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
  UnitTests/CommonTestUtils/ReferenceRepository.cs
  contributors.txt
Labels: :pen: status: cla signed, hacktoberfest-accepted

#9583 Select HOME where .gitconfig is accessible first
  GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
Labels: hacktoberfest-accepted

#9539 Simplify the ISettingsSource class
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/ConfigFileSettings.cs
  GitCommands/Settings/RepoDistSettings.cs
  GitCommands/Settings/Setting.cs
  GitCommands/Settings/SettingsCache.cs
  GitCommands/Settings/SettingsContainer.cs
  GitCommands/Settings/SettingsPath.cs
  GitUI/Plugin/GitPluginSettingsContainer.cs
  Plugins/GitUIPluginInterfaces/ISettingsSource.cs
  Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
  Plugins/Gource/GourcePlugin.cs
  UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Labels: hacktoberfest-accepted

#9564 NBug: Include GE specific exception info
  BugReporter/BugReportForm.cs
  BugReporter/ErrorReportMarkDownBodyBuilder.cs
  BugReporter/GitHubUrlBuilder.cs
  BugReporter/Program.cs
  GitCommands/Settings/AppSettings.cs
  GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
  GitUI/NBugReports/BugReportInvoker.cs
  IntegrationTests/BugReporter.IntegrationTests/BugReportFormTests.cs
  UnitTests/GitUI.Tests/NBugReports/BugReportInvokerTests.cs
Labels: hacktoberfest-accepted

#9603 Add keyboard hotkeys to one menu and one dialog
  GitUI/BranchTreePanel/ContextMenu/MenuItemsStrings.cs
  GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
  GitUI/Translation/English.xlf
  contributors.txt
Labels: :pen: status: cla signed, hacktoberfest-accepted

#9698 Reset another branch to here path format
  GitCommands/Git/Commands/GitCommandHelpers.cs
  UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Labels: status: auto merge

#9686 `Rebase --onto`: Display only the current branch to make selection easier
  GitUI/CommandsDialogs/FormRebase.cs
  GitUI/HelperDialogs/FormChooseCommit.cs
Labels: status: auto merge, hacktoberfest-accepted

#9580 Sync advanced filter and filters toolbar
  GitCommands/Git/GitVersion.cs
  GitCommands/RevisionReader.cs
  GitExtensionsTest.ruleset
  GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
  GitUI/BranchTreePanel/RepoObjectsTree.cs
  GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
  GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormFileHistory.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FilterToolBar.cs
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/FilterChangedEventArgs.cs
  GitUI/UserControls/RevisionGrid/FilterInfo.cs
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
  GitUI/UserControls/RevisionGrid/FormRevisionFilter.resx
  GitUI/UserControls/RevisionGrid/IRevisionGridFilter.cs
  GitUI/UserControls/RevisionGrid/RevisionFilter.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.RevisionGridInMemFilter.cs
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
  IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
  UnitTests/GitUI.Tests/UserControls/FilterInfoTests.FilterInfo_ctor_expected.approved.txt
  UnitTests/GitUI.Tests/UserControls/FilterInfoTests.FilterInfo_ctor_with_Raw_expected.approved.txt
  UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
  UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
Labels: hacktoberfest-accepted

#9608 Fix branch copy and Open with difftool menu switching back to System style
  GitExtUtils/GitUI/ToolStripExtensions.cs
  contributors.txt
Labels: :pen: status: cla signed, status: auto merge, hacktoberfest-accepted

#9680 GitVersion: Remove support for obsolete versions
  GitCommands/CommitDataManager.cs
  GitCommands/Git/Commands/GitCommandHelpers.cs
  GitCommands/Git/GetAllChangedFilesOutputParser.cs
  GitCommands/Git/GitModule.cs
  GitCommands/Git/GitVersion.cs
  GitCommands/RevisionReader.cs
  GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
  GitUI/CommandsDialogs/FormBrowse.cs
  GitUI/CommandsDialogs/FormClone.Designer.cs
  GitUI/CommandsDialogs/FormClone.cs
  GitUI/CommandsDialogs/FormMergeBranch.cs
  GitUI/CommandsDialogs/FormPush.cs
  GitUI/CommandsDialogs/FormResolveConflicts.cs
  GitUI/CommandsDialogs/FormStash.cs
  GitUI/CommandsDialogs/FormVerify.LostObject.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
  GitUI/Translation/English.xlf
  Plugins/GitUIPluginInterfaces/GitRevision.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  UnitTests/GitCommands.Tests/CommitDataManagerTest.cs
  UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
  UnitTests/GitCommands.Tests/GitModuleTests.cs
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.empty_commit.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.multi_pathfilter.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.no_subject.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.normal.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.simple_pathfilter.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.subject_no_body.approved.json
  UnitTests/GitCommands.Tests/RevisionReaderTests.cs
  UnitTests/GitCommands.Tests/TestData/RevisionReader/empty_commit.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/multi_pathfilter.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/no_encoding.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/no_subject.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/normal.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/simple_pathfilter.bin
  UnitTests/GitCommands.Tests/TestData/RevisionReader/subject_no_body.bin
Labels: hacktoberfest-accepted
