Repository gitextensions/gitextensions, pull requests merged in 2022-04, with the labels that each got.

#9932 Increase contrast between graph colors
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
Labels: area: user experience

#9933 CommitInfo: Clear RevisionInfo if no real revision
  GitUI/CommitInfo/CommitInfo.cs
Labels: type: regression

#9963 Migrates FabricBot automation to "Config-as-Code"
  .github/fabricbot.json
Labels: status: auto merge, area: toolchain
