Repository gitextensions/gitextensions, pull requests merged in 2023-08, with the labels that each got.

#11120 #10992 noFastForward disabled in UI when Squash is checked
  GitUI/CommandsDialogs/FormMergeBranch.cs
Labels: :pen: status: cla signed

#11134 Hide build server status tab if not configured
  Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerSettings.cs
Labels: release-notes-worthy

#11169 Use the correct interface of JContainer for indexer
  Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
Labels: type: regression
