Repository gitextensions/gitextensions, pull requests merged in 2024-04, with the labels that each got.

#11239 Allow user scripts to operate on selected files
  GitCommands/StringExtensions.cs
  GitUI/CommandsDialogs/FormCommit.Designer.cs
  GitUI/CommandsDialogs/FormCommit.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
  GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  GitUI/CommandsDialogs/ScriptOptionsProvider.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
  GitUI/GitModuleControl.cs
  GitUI/GitModuleForm.cs
  GitUI/LeftPanel/RepoObjectsTree.ContextActions.cs
  GitUI/ScriptsEngine/IScriptOptionsProvider.cs
  GitUI/ScriptsEngine/IScriptsRunner.cs
  GitUI/ScriptsEngine/ScriptEvent.cs
  GitUI/ScriptsEngine/ScriptsManager.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
  UnitTests/GitCommands.Tests/StringExtensionTests.cs
Labels: :eyeglasses: status: needs review, status: ready, release-notes-worthy

#11680 fix finding merge base when unrelated history
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: :mailbox_with_no_mail: needs: author feedback

#11677 Difftastic as diff viewer
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitCommands/Settings/DiffDisplayAppearance.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
  GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
  GitUI/Editor/Diff/AnsiEscapeUtilities.cs
  GitUI/Editor/Diff/DiffHighlightService.cs
  GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
  GitUI/Editor/Diff/DifftasticHighlightService.cs
  GitUI/Editor/Diff/PatchHighlightService.cs
  GitUI/Editor/FileViewer.Designer.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/ViewMode.cs
  GitUI/Editor/ViewModeExtension.cs
  GitUI/GitUIExtensions.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Properties/Images.Designer.cs
  GitUI/Properties/Images.resx
  GitUI/Resources/Icons/difftastic.ico
  GitUI/Resources/Icons/edit-color.png
  GitUI/Translation/English.xlf
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
  UnitTests/GitUI.Tests/Editor/Diff/DiffLineNumAnalyzerTests.cs
  UnitTests/GitUI.Tests/Editor/Diff/SampleDifftastic.diff
Labels: release-notes-worthy
