Repository gitextensions/gitextensions, pull requests merged in 2024-01, with the labels that each got.

#11415 Fix failure to add repository path as safe directory
  GitUI/NBugReports/BugReportInvoker.cs
  contributors.txt
Labels: :pen: status: cla signed, :mailbox_with_no_mail: needs: author feedback, status: abandoned

#11515 Fixup limits by RevisionGraph.Count
  GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: :eyeglasses: status: needs review, status: ready

#11516 Simplify RevisionDataGridView.LoadingCompleted
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: :eyeglasses: status: needs review, status: ready

#11482 Check for cancellation before accessing non-locals
  GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: :eyeglasses: status: needs review, status: ready

#11529 Do not update graph cache if row unavailable
  GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
  GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Labels: :eyeglasses: status: needs review, :grey_exclamation: priority: high, status: ready

#11552 Ignore ListViewGroup accessibility exception
  GitUI/NBugReports/BugReportInvoker.cs
Labels: :eyeglasses: status: needs review, status: ready
