Repository gitextensions/gitextensions, pull requests merged in 2024-03, with the labels that each got.

#11637 Support F# files
  Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
  contributors.txt
Labels: area: plugins, :scroll: status: needs cla

#11655 Fix theme migration bug
  Plugins/GitUIPluginInterfaces/SettingsSource.cs
  UnitTests/GitUI.Tests/Theming/AppColorDefaultsTests.cs
  contributors.txt
Labels: :pen: status: cla signed

#11652 Improve stability of show stashes test
  IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
Labels: :eyeglasses: status: needs review, status: ready

#11350 git-grep UI
  GitCommands/Git/GitModule.cs
  GitCommands/Settings/AppSettings.cs
  GitExtUtils/GitCommandConfiguration.cs
  GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
  GitUI/CommandsDialogs/RevisionDiffControl.cs
  GitUI/Editor/Diff/AnsiEscapeUtilities.cs
  GitUI/Editor/Diff/CombinedDiffHighlightService.cs
  GitUI/Editor/Diff/DiffLineType.cs
  GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
  GitUI/Editor/Diff/GrepHighlightService.cs
  GitUI/Editor/Diff/PatchHighlightService.cs
  GitUI/Editor/FileViewer.cs
  GitUI/Editor/FileViewerInternal.cs
  GitUI/Editor/FormSearchCommit.Designer.cs
  GitUI/Editor/FormSearchCommit.cs
  GitUI/Editor/FormSearchCommit.resx
  GitUI/Editor/ViewMode.cs
  GitUI/Editor/ViewModeExtension.cs
  GitUI/GitUIExtensions.cs
  GitUI/Hotkey/HotkeySettingsManager.cs
  GitUI/Translation/English.xlf
  GitUI/UserControls/FileStatusDiffCalculator.FileStatusDiffCalculatorInfo.cs
  GitUI/UserControls/FileStatusDiffCalculator.cs
  GitUI/UserControls/FileStatusList.Designer.cs
  GitUI/UserControls/FileStatusList.cs
  Plugins/GitUIPluginInterfaces/GitItemStatus.cs
  Plugins/GitUIPluginInterfaces/IGitModule.cs
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetDefaultStatus.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=added_by_them.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=added_by_us.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=both_added.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=both_deleted.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=both_modified.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=deleted_by_them.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=deleted_by_us.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=fatal_error.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=status_ignored_files.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=status_modified_files.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=status_staged_files.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=status_untracked_files.verified.json
  UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString_testName=status_with_spaces.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_deleted.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_getdefaults.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_new.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_none.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_renamed.verified.json
  UnitTests/GitCommands.Tests/Git/GitRevisionTesterTests.ReverseSelection_expected_changes_unmerged.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Check_that_spaces_are_not_trimmed_in_file_names.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Check_that_the_staged_status_is_None_if_not_IndexWorkTree1.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Check_that_the_staged_status_is_None_if_not_IndexWorkTree2.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Ignore_unmerged_in_conflict_if_revision_is_work_tree.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Include_unmerged_in_conflict_if_revision_is_index.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=Rename_with_spaces.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=WorkTree1.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=WorkTree2.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=WorkTree3.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=WorkTree4.verified.json
  UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString_testName=fatal_error.verified.json
  UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
  UnitTests/GitUI.Tests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs
Labels: release-notes-worthy
