Repository gitextensions/gitextensions, pull requests merged in 2024-06, with the labels that each got.

#11785 FormCommit: Fixup cursor movement in message editor
  src/app/GitUI/SpellChecker/EditNetSpell.Designer.cs
  src/app/GitUI/UserControls/TextBoxSilencer.cs
Labels: :eyeglasses: status: needs review, status: ready

#11759 Fix: Correct ProjectId retrieval in GitLab BuildServerIntegration due…
  contributors.txt
  src/plugins/BuildServerIntegration/GitlabIntegration/ApiClient/GitlabApiClient.cs
  src/plugins/BuildServerIntegration/GitlabIntegration/Settings/GitlabRemoteParser.cs
  tests/plugins/UnitTests/BuildServerIntegration/GitlabIntegration.Tests/GitlabRemoteParserTests.cs
Labels: :pen: status: cla signed

#11791 fix(DiffMergeTools): path for diff/merge command
  contributors.txt
  src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
Labels: :pen: status: cla signed

#11773 feat(ScriptOptionsProvider): {SelectedRelativePaths}
  src/app/GitUI/CommandsDialogs/FormCommit.cs
  src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
  src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
  src/app/GitUI/CommandsDialogs/ScriptOptionsProvider.cs
  src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
  src/app/GitUI/Translation/English.xlf
Labels: release-notes-worthy
