Repository gitextensions/gitextensions, pull requests merged in 2025-05, with the labels that each got.

#12328 fix(FileViewer): Actually go to first change
  src/app/GitUI/Editor/FileViewer.cs
  src/app/GitUI/Editor/FileViewerInternal.cs
Labels: area: user experience, type: regression

#12344 fix(message editor): Disable URL detection
  src/app/GitUI/SpellChecker/EditNetSpell.Designer.cs
Labels: area: user experience

#12343 fix(LeftSplitContainer): Workaround shift on load
  src/app/GitUI/CommandsDialogs/FormBrowse.cs
Labels: area: user experience

#12342 feat(reset current branch): Update submodules if not disabled
  src/app/GitUI/HelperDialogs/FormResetCurrentBranch.cs
Labels: area: submodules

#12341 feat(file tree): Provide git-grep
  src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
  src/app/GitUI/UserControls/FileStatusList.ContextMenu.cs
  src/app/GitUI/UserControls/FileStatusList.cs
  src/app/GitUI/UserControls/MultiSelectTreeView.cs
Labels: area: user experience

#12282 Add more keyboard mnemonics
  src/app/GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
  src/app/GitUI/CommandsDialogs/FormClone.Designer.cs
  src/app/GitUI/CommandsDialogs/FormPull.cs
  src/app/GitUI/CommandsDialogs/FormPush.Designer.cs
  src/app/GitUI/CommandsDialogs/FormRemotes.Designer.cs
  src/app/GitUI/CommandsDialogs/FormRemotes.cs
  src/app/GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
  src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.Designer.cs
  src/app/GitUI/LeftPanel/RepoObjectsTree.Designer.cs
  src/app/GitUI/Translation/English.xlf
  src/app/GitUI/UserControls/FolderBrowserButton.Designer.cs
  src/app/GitUI/UserControls/FolderBrowserButton.cs
Labels: area: user experience, :mailbox_with_no_mail: needs: author feedback

#12356 fix(WSL): Make "edit commit" & "reword commit" work
  src/app/GitCommands/Utils/WslUtil.cs
  src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Labels: area: wsl

#12383 fix(FindAndReplaceForm): Make multi-file search cancelable
  src/app/GitUI/Editor/FindAndReplaceForm.cs
Labels: area: user experience

#12391 fix(GitConfigSettingsBase): Fixup race condition
  src/app/GitCommands/Settings/GitConfigSettingsBase.cs
Labels: type: regression
